void BACKDOOR_MGR_GetChar(void){return;}
void BACKDOOR_MGR_Printf(void){return;}
void BACKDOOR_MGR_Register_SubsysBackdoorFunc_CallBack(void){return;}
void BUFFER_MGR_Allocate(void){return;}
void BUFFER_MGR_Free(void){return;}
void FS_OM_AddControlFilePtr(void){return;}
void FS_OM_AddControlSeqNo(void){return;}
//void FS_OM_AddFileHeader(void){return;}
//void FS_OM_AllocateFileHeaderBuffer(void){return;}
void FS_OM_AttachSystemResources(void){return;}
void FS_OM_ClearControlAttribution(void){return;}
void FS_OM_GetCommSemaphore(void){return;}
void FS_OM_GetControlAttrCheckSum(void){return;}
void FS_OM_GetControlAttrFileName(void){return;}
void FS_OM_GetControlAttrFileSize(void){return;}
void FS_OM_GetControlAttrFileType(void){return;}
void FS_OM_GetControlAttrPrivilage(void){return;}
void FS_OM_GetControlAttribution(void){return;}
void FS_OM_GetControlDriverId(void){return;}
void FS_OM_GetControlFileBuffer(void){return;}
void FS_OM_GetControlFilePtr(void){return;}
void FS_OM_GetControlFlashOperation(void){return;}
void FS_OM_GetControlFlashResult(void){return;}
void FS_OM_GetControlSeqNo(void){return;}
void FS_OM_GetControlStackingMode(void){return;}
void FS_OM_GetControlState(void){return;}
//void FS_OM_GetDebugFlag(void){return;}
void FS_OM_GetFileChecksum(void){return;}
//void FS_OM_GetFileHeaderByName(void){return;}
void FS_OM_GetInitStatus(void){return;}
void FS_OM_GetNextFileHeaderByName(void){return;}
void FS_OM_GetONIEInstallerDebugFlag(void){return;}
void FS_OM_GetSemaphore(void){return;}
void FS_OM_GetShutdownFlag(void){return;}
//void FS_OM_GetStartupName(void){return;}
void FS_OM_GetTaskId(void){return;}
void FS_OM_INIT_GetShMemInfo(void){return;}
void FS_OM_InitateVariables(void){return;}
void FS_OM_InitiateSystemResources(void){return;}
void FS_OM_MinusControlAttrFileSize(void){return;}
//void FS_OM_RemoveFileHeaderByName(void){return;}
void FS_OM_SetControlAttribution(void){return;}
void FS_OM_SetControlDriverId(void){return;}
void FS_OM_SetControlFileBuffer(void){return;}
void FS_OM_SetControlFilePtr(void){return;}
void FS_OM_SetControlFlashOperation(void){return;}
void FS_OM_SetControlFlashResult(void){return;}
void FS_OM_SetControlStackingMode(void){return;}
void FS_OM_SetControlState(void){return;}
void FS_OM_SetDebugFlag(void){return;}
void FS_OM_SetFileChecksum(void){return;}
void FS_OM_SetInitStatus(void){return;}
void FS_OM_SetONIEInstallerDebugFlag(void){return;}
void FS_OM_SetShutdownFlag(void){return;}
//void FS_OM_SetStartupName(void){return;}
void FS_OM_SetTaskId(void){return;}
void ISC_RemoteCall(void){return;}
void ISC_RemoteReply(void){return;}
void ISC_SendMcastReliable(void){return;}
void L_CHARSET_IsValidFileNameString(void){return;}
void L_CHARSET_TrimTrailingNonPrintableChar(void){return;}
void L_MM_DebugPrintf(void){return;}
void L_MM_Malloc(void){return;}
void STKTPLG_POM_GetMyUnitID(void){return;}
void STKTPLG_POM_GetNextUnit(void){return;}
void SW_WATCHDOG_MGR_RegisterMonitorThread(void){return;}
void SW_WATCHDOG_MGR_ResetTimer(void){return;}
void SYSFUN_CreateMsgQ(void){return;}
int SYSFUN_ExecuteSystemShellEx(void){return 0;}
void SYSFUN_GetExecuteCmdOutput(void){return;}
void SYSFUN_GetRealAOSShellCmd(void){return;}
void SYSFUN_GiveSem(void){return;}
void SYSFUN_ReceiveEvent(void){return;}
void SYSFUN_SendEvent(void){return;}
void SYSFUN_Sleep(void){return;}
void SYSFUN_Sleep_Interruptible(void){return;}
void SYSFUN_SpawnThread(void){return;}
void SYSFUN_TakeSem(void){return;}
void SYS_TIME_GetUtcRealTimeBySec(void){return;}
void UC_MGR_GetSysInfo(void){return;}
void UC_MGR_SetDirtySignature(void){return;}
void _L_MM_AllocateTxBuffer(void){return;}
void _L_MM_Free(void){return;}
void _L_MM_Mref_GetPdu(void){return;}
void _L_MM_Mref_Release(void){return;}
void _L_MM_Mref_SetPduLen(void){return;}
