#ifndef IML_TYPE_H
#define IML_TYPE_H

enum
{
    IML_TYPE_RETVAL_OK,
    IML_TYPE_RETVAL_NET_DEVICE_NOT_EXIST,
    IML_TYPE_RETVAL_MREF_ERROR,
    IML_TYPE_RETVAL_ALLOC_SKB_FAIL,
    IML_TYPE_RETVAL_INVALID_ARG,
    IML_TYPE_RETVAL_INTR,
    IML_TYPE_RETVAL_L_MM_ALLOCATE_TX_BUFFER_FAIL,
    IML_TYPE_RETVAL_TX_BUF_FULL,
    IML_TYPE_RETVAL_TX_BUF_EMPTY,
    IML_TYPE_RETVAL_UNKNOWN_SYSCALL_CMD,
    IML_TYPE_RETVAL_GET_VID_FROM_VLAN_DEV_ERROR,
    IML_TYPE_RETVAL_UNKNOWN_ERROR
};

/* definitions of result of the operation in IPC call
 */
enum
{
    IML_TYPE_RESULT_OK=0,
    IML_TYPE_RESULT_FAIL
};

enum
{
    IML_TYPE_SYSCALL_CMD_SEND_PKT_TO_TCP_IP_STACK,
    IML_TYPE_SYSCALL_CMD_RECV_PKT_FROM_TCP_IP_STACK
};

enum
{
    IML_TYPE_TRACE_ID_ENQ_TO_IP_PKT_LIST,
    IML_TYPE_TRACE_ID_PACKET_DISPATCH,
    IML_TYPE_TRACE_ID_PACKET_DISPATCH_MLD    
};

enum
{
    IML_TYPE_PROCESS_PACKET_DIRECT_CALL = 0,
    IML_TYPE_PROCESS_PACKET_NETIF_RX_WAIT,
    IML_TYPE_PROCESS_PACKET_NETIF_RX_NO_WAIT,
};

#endif

