/* MODULE NAME:  foundry_sn_ip.h
 *
 * PURPOSE: For SNMP to access Brocade's FOUNDRY-SN-IP-MIB:
 *
 * foundry(1991).products(1).router(2).snIp(2)
 *
 * NOTES:
 *
 * HISTORY (mm/dd/yyyy)
 *    05/30/2011 - Qiyao Zhong, Created
 *
 * Copyright(C)      Accton Corporation, 2011
 */

/* Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.4 2004/07/28 08:04:58 dts12 Exp $
 */
#ifndef FOUNDRY_SN_IP_H
#define FOUNDRY_SN_IP_H

/* function declarations
 */

/* ------------------------------------------------------------------------
 * SCALAR NODES - 1.2.2.1 snRtIpGeneral.*
 * ------------------------------------------------------------------------
 */
void init_snRtClearArpCache(void);  /* 1 */
Netsnmp_Node_Handler do_snRtClearArpCache;

/* ------------------------------------------------------------------------
 * FUNCTION NAME - init_snIp
 * ------------------------------------------------------------------------
 * PURPOSE  :   This is the entry point into this file for initialisation.
 *
 * INPUT    :   None.
 *
 * OUTPUT   :   None.
 *
 * RETURN   :   None.
 *
 * NOTES    :   None.
 * ------------------------------------------------------------------------
 */
void init_snIp(void);

#endif  /* FOUNDRY_SN_IP_H */
