#ifndef _CONFIG_AGENT_HEADER_PRIVATE_CONFIG_H_
#define _CONFIG_AGENT_HEADER_PRIVATE_CONFIG_H_

#define CONFIG_AGENT_HAVE_BSON 1
//#define CONFIG_AGENT_HAVE_LIBUCL 1

/* #undef CONFIG_AGENT_HAVE_PCRE */
#define CONFIG_AGENT_HAVE_PCRE2 1

#endif /* _CONFIG_AGENT_HEADER_PRIVATE_CONFIG_H_ */
