

/***************************************************************************/
/*               message string structure definitions                      */
/***************************************************************************/
char *uis_promptMsg[] =
{
    /* UI_MSG_COPYRIGHT_STR */
    "Copyright(C) 2000-2002",

    /* UI_MSG_PRESS_ENTER_STR */
    "Press ENTER key to start a new session",

    /* UI_MSG_KEY_CONFIRM */
    "Use TAB or Cursor keys to move, <Enter> to confirm.",

    /* UI_MSG_KEY_SELECT */
    "Use TAB or Cursor keys to move, <Space> to select.",

    /* UI_MSG_KEY_EDIT */
    "<Ctrl-F> forward a char, <Ctrl-B> backward a char.",

    /* UI_MSG_SET_OPER_CONF */
    "Are you sure you want to perform this operation? (y/n) ",
   
    /* UI_MSG_SET_CONF_NO */
    "User quit. Operation not performed.",

    /* UI_MSG_TFTP_START */
    "TFTP download session started. System will reboot when completed ...",

    /* UI_MSG_TFTP_COMPLETE */
    "TFTP download successfully. Starting new code now ...",
    
    /* UI_MSG_XMODEM_PROCESSING */
    "Receiving image ...",
        
    /* UI_MSG_XMODEM_COMPLETE */
    "XMODEM download successfully.  Starting new code now ...",

    /* UI_MSG_WAIT_FLASH_WRITE */
    "Writing microcode to flash memory. Please wait ...",

    /* UI_MSG_EXIT_RESTART */
    "System is going to restart.",

    /* UI_MSG_EXIT_RECONNECT */
    "If you want to return to command line interface program,",

    /* UI_MSG_EXIT_REST_CNT */
    "connect to the system after restarting completed.",

    /* UI_MSG_EXIT_REST_ENT */
    "press <Enter> repeatedly after restarting completed.",

    /* UI_MSG_EXIT_TIMEOUT */
    "Timeout.",

    /* UI_MSG_EXIT_LOGIN */
    "WARNING: Too many failed logon attempts.",

    /* UI_MSG_EXIT_FAIL_CON */
    "Connect failed.",

    /* UI_MSG_EXIT_IP_CHANGED */
    "IP is changed now.",

    /* UI_MSG_EXIT_EEDEF_OK */
    "Set EEPROM to default value.",

    /* UI_MSG_EXIT_EEDEF_FAIL */
    "IAD need to be stand alone when set EEPROM to default value.",

    /* UI_MSG_EXIT_USER_ACT */
    "You have exited from commnad line interface program.",

    /* UI_MSG_EXIT_CONNECT */
    "connect to the system again.",

    /* UI_MSG_EXIT_REENTER */
    "press ENTER key to continue",

};


/*integrate all prompt message
 */
char *Cli_PromptMsg[] =
{
   /* 0: CLI_PMT_INVALID_PASSWORD */
   "Incorrect password",
  
  /* 1: CLI_PMT_LOGIN_FAIL  */
   "WARNING:  Too many failed logon attempts",
   
  /* 2: CLI_PMT_LOGIN_FAIL_HANG */
   "Management Console is now temporarily disabled.\r\nCall your network adminstrator for assistance.",

  /* 3 : CLI_PMT_FLASH_READ_FAIL */
   "Error: Flash reading fail\r\n",
   
  // 4: CLI_PMT_FLASH_WRITING_FAIL,
   "Error:Flash writing fail\r\n",
   
  // 5: CLI_PMT_DIFF_SUBNET
   "The setting default gateway IP address must be in the same subnet as IP address.\r\n",
  
  // 6: CLI_PMT_FILENAME_TOO_LONG
   "Error: Filename too long (max 80 characters)\r\n",
   
  // 7: CLI_PMT_STRING_TOO_LONG 
   "Error: String too long (max 255 characters)\r\n",
   
  // 8: CLI_PMT_DESCRIPT_TOO_LONG
   "Error: Description too long (max 20 characters)\r\n",
   
  // 9: CLI_PMT_ILLEGAL_IP
   "Error: Illegal IP address\r\n", 
   
  // 10: CLI_PMT_INVALID_PARAMETER
  "Error: Invalid parameter\r\n",
  
  // 11: CLI_PMT_SKIP_SYSTEM_UNSTABLE, 
  "Error: System is not stable, please retry it later\r\n",
  
  // 12: CLI_PMT_RESET_COUNT_FAIL
  "Error: Reset counter fail\r\n",
  
  //13: CLI_PMT_INVALID_HUB_NUM,
  "Error: Invalid IAD number\r\n",
  
  //14: CLI_PMT_INVALID_PORT_NUM,
  "Error: Invalid port number\r\n",
  
  //15: CLI_PMT_INVALID_PASS_LEN,
  "Error: Invalid password length.\r\n       Password length must be between 4 and 8 characters\r\n",
  
  //16: CLI_PMT_ILLEGAL_SUBNET,
   "Error: Illegal subnet mask IP address\r\n",
   
  //17 CLI_PMT_APPLY_IP_FAIL
   "Error: IP setting fail\r\n", 
   
  //18: CLI_PMT_BOOTP_NOT_CHANGE_IP,
   "Error: IP change is not allowed in bootp state\r\n",
   
  //19: CLI_PMT_COMMUNITY_TOO_LONG
  "Error: Community string is too long (max 32 characters)\r\n", 
    
  //20: CLI_PMT_COMMUNITY_NOT_FOUND
  "Error: Community string not found\r\n",
  
  //21: CLI_PMT_SNMP_HOST_NOT_FOUND
  "Error: Host not found\r\n",
  
  //22: CLI_PMT_OUT_OF_ADDRESS,
  "Error: Out of addressable range\r\n",
  
 
};



char *Cli_ErrMsg[] =
{
    /* 0: CLI_NO_ERROR */
    "",

    /* 1: CLI_USE_DEFAULT */
    "Use default value : ",

    /* 2: CLI_ERR_CMD_INCOMPLETE */
    "Incomplete command.",

    /* 3: CLI_ERR_CMD_INVALID */
    "Invalid input detected at '^' marker.",

    /* 4: CLI_ERR_CMD_AMBIGUOUS */
    "Ambiguous command : ",

    /* 5: CLI_ERR_CMD_UNRECOGNIZED */
    "Unrecognized command.",

    /* 6: CLI_ERR_CMD_SHOW_QUMARK  */
    "Type \"show ?\" for a list of subcommands.",

    /* 7: CLI_ERR_CMD_INVALID_RANGE*/
    "Invalid parameter value/range. Type \"?\" to get more detail information.",

    /* 8: CLI_ERR_CMD_NOT_IMPLEMENT */
    "Internal: Command not implement yet",
    
    /* 9: CLI_ERR_CMD_BYPASS_MATCHED */
    "Bypass matched",
    
    /* 10: CLI_ERR_INFINITE_LOOP  */
    "Infinite loop",
    
    /* 11: CLII_ERR_MEMORY_NOT_ENOUGH */
    "Memory is not enough",
    
    /* 12. CLI_ERR_TIMEOUT */
    "Timeout.",
    
    /* 13: CLI_ERR_INTERNAL*/
    "CLI internal error; please contact with system administrator",
    
    /* 14:   CLI_EXIT_SESSION*/
    "CLI exit session",

    /* 15: CLI_ERR_CMD_INVALID_RANGE_PLUS*/
    "Invalid parameter value/range input detected at '^' marker.",

    /* 16: CLI_ERR_CMD_ARG_AMBIGUOUS*/
    "Ambiguous command and argument.",

};


/***************************************************************************/
/*                                                                         */
/*              Help message structure definitions                         */
/*                                                                         */
/***************************************************************************/
char *ui_HelpMsg[] =
{
/*0*/   "Turns on privileged commands",
/*1*/   "Privileged EXEC",
/*2*/   "Exits from the EXEC",
/*3*/   "Description of the interactive help system",
/*4*/   "Sends ICMP echo request packets to another host",
/*5*/   "Destination IP address",
/*6*/   "Specifies the number of packets to send",
/*7*/   "Number of packets to send",
/*8*/   "Specifies the size of the data portion",
/*9*/   "Size of the data portion",
/*10*/   "Exits a CLI session",
/*11*/   "Shows information",
/*12*/   "History information",
/*13*/   "Interface information",
/*14*/   "Interface counters information",
/*15*/   "Ethernet port",
/*16*/   "Unit number#Port number",
/*17*/   "Status of the specified port-channel",
/*18*/   "Port-channel interface number",
/*19*/   "Interface status information",
/*20*/   "Status of specified VLAN Interface",
/*21*/   "VLAN interface number",
/*22*/   "Interface switchport information",
/*23*/   "IP information",
/*24*/   "LACP statistics",
/*25*/   "Channel group",
/*26*/   "Shows statistics for LACP protocol messages",
/*27*/   "Shows config settings/operational state for local side",
/*28*/   "Shows config settings/operational state for remote side",
/*29*/   "Shows channel groups system priority/MAC address",
/*30*/   "TTY line information",
/*31*/   "Console terminal line parameters",
/*32*/   "Parameters for virtual terminal",
/*33*/   "Simple Network Management Protocol statistics",
/*34*/   "System information",
/*35*/   "Information about terminal lines",
/*36*/   "System hardware and software versions",
/*37*/   "Unit number",
/*38*/   "Virtual LAN settings",
/*39*/   "VLAN interface",
/*40*/   "VLAN ID",
/*41*/   "VLAN interface name",
/*42*/   "VLAN name",
/*43*/   "Specifies packets to drop",
/*44*/   "Specifies IP address",
/*45*/   "Specifies any source IP address",
/*46*/   "Specifies MAC address",
/*47*/   "Specifies any source MAC address",
/*48*/   "Logs a packet when it matches the access control entry",
/*49*/   "Specifies the source host as a single MAC address",
/*50*/   "Specifies source MAC address",
/*51*/   "Specifies source MAC address, to be followed by a bit mask",
/*52*/   "Specifies source MAC bitmask",
/*53*/   "Specifies the source host as a single IP address",
/*54*/   "Source IP address",
/*55*/   "Specifies source IP address, to be followed by a bit mask",
/*56*/   "Specifies source bit mask (ex: 255.255.255.0)",
/*57*/   "Specifies a match for ARP request",
/*58*/   "Specifies a match for ARP responses",
/*59*/   "Specifies any destination IP address",
/*60*/   "Specifies any destination MAC",
/*61*/   "Specifies the destination host as a single MAC address",
/*62*/   "Specifies destination MAC address",
/*63*/   "Specifies destination MAC address, to be followed by a bit mask",
/*64*/   "Specifies destination MAC bitmask (ex:ff-ff-ff-00-00-00)",
/*65*/   "Specifies the destination host as a single IP address",
/*66*/   "Destination address",
/*67*/   "Specifies destination IP address, to be followed by a bit mask",
/*68*/   "Specifies destination bit mask",
/*69*/   "Exits from configure mode",
/*70*/   "Exits from access-list configure mode",
/*71*/   "Negates a command or sets its defaults",
/*72*/   "Specifies packets to permit",
/*73*/   "Any source IP address",
/*74*/   "Any destination host",
/*75*/   "Specifies destination port",
/*76*/   "Specifies destination port number",
/*77*/   "Specifies destination port bitmask",
/*78*/   "Specifies DSCP",
/*79*/   "Specifies DSCP value",
/*80*/   "Specifies source port",
/*81*/   "Specifies source port number",
/*82*/   "Specifies source port bitmask",
/*83*/   "Specifies precedence",
/*84*/   "Specifies precedence value",
/*85*/   "Specifies ToS",
/*86*/   "Specifies ToS value",
/*87*/   "Specifies destination host",
/*88*/   "Specifies source host",
/*89*/   "Specifies protocol as ICMP",
/*90*/   "Specifies ICMP type",
/*91*/   "Specifies ICMP type number",
/*92*/   "Configures MAC parameters",
/*93*/   "Specifies VLAN ID",
/*94*/   "Specifies VLAN ID value",
/*95*/   "Specifies destination port bit mask",
/*96*/   "Specifies source port bit mask",
/*97*/   "Specifies protocol",
/*98*/   "Specifies protocol value",
/*99*/   "Specifies source bit mask (ex.: 255.255.255.0)",
/*100*/   "Specifies protocol as TCP",
/*101*/   "Specifies control flag",
/*102*/   "Specifies decimal control flag value (ex.: 18 to specify SYN and ACK bits on)",
/*103*/   "Specifies decimal control flag bit mask (ex.: 18 to specify to check SYN and ACK bits)",
/*104*/   "Specifies protocol as UDP",
/*105*/   "Specifies VLAN ID bit mask",
/*106*/   "Specifies decimal control flag value (ex: 18 to specify SYN and ACK bits on)",
/*107*/   "Specifies decimal control flag bitmask (ex: 18 to specify to check SYN and ACK bits)",
/*108*/   "Information on the running configuration",
/*109*/   "An abbreviation for the IPv6 prefix ::/0",
/*110*/   "Specifies next-header",
/*111*/   "Specifies next-header value",
/*112*/   "Configures destination host",
/*113*/   "Specifies destination IPv6 address",
/*114*/   "Destination IPv6 network or class of networks",
/*115*/   "Any source MAC",
/*116*/   "Any destination MAC",
/*117*/   "Specifies ethertype",
/*118*/   "Specifies ethertype value, used as hex",
/*119*/   "Specifies ethertype bit mask, used as hex",
/*120*/   "Specifies destination MAC bit mask",
/*121*/   "Specifies packet format as tagged-802.3",
/*122*/   "Specifies source MAC bit mask",
/*123*/   "Specifies packet format as tagged-eth2",
/*124*/   "Specifies packet format as untagged-802.3",
/*125*/   "Specifies packet format as untagged-eth2",
/*126*/   "Exits from privilege EXEC mode",
/*127*/   "An abbreviation for the source IPv6 prefix ::/0",
/*128*/   "Configures source host",
/*129*/   "Specifies source IPv6 address",
/*130*/   "Source IPv6 network or class of networks",
/*131*/   "Defines the description of class-map",
/*132*/   "64 characters at most",
/*133*/   "Returns to privileged EXEC mode",
/*134*/   "Exits from class map configure mode",
/*135*/   "Defines the match criteria to classify traffic",
/*136*/   "Specifies access-list name",
/*137*/   "Access-list name",
/*138*/   "Specifies user priority",
/*139*/   "Specifies user priority value",
/*140*/   "Specifies IP DSCP or precedence",
/*141*/   "DSCP value",
/*142*/   "Precedence value",
/*143*/   "Deletes the description of class-map",
/*144*/   "Redefines the name of class-map",
/*145*/   "Class map name",
/*146*/   "Removes a policy map",
/*147*/   "Input direction",
/*148*/   "Policy map name",
/*149*/   "Applies a policy map",
/*150*/   "Access lists",
/*151*/   "Specifies ARP ACLs",
/*152*/   "ARP access-list name",
/*153*/   "Specifies IP ACLs",
/*154*/   "Specifies an extended IP ACL",
/*155*/   "ACL name",
/*156*/   "Specifies a standard IP ACL",
/*157*/   "Specifies IPv6 ACLs",
/*158*/   "Specifies an extended IPv6 ACL",
/*159*/   "Specifies a standard IPv6 ACL",
/*160*/   "Specifies MAC ACLs",
/*161*/   "Address Resolution Protocol",
/*162*/   "IP address",
/*163*/   "Hardware address",
/*164*/   "Configures ARP timeout",
/*165*/   "Specifies ARP timeout",
/*166*/   "Authentication method",
/*167*/   "Authentication enable method",
/*168*/   "Local database",
/*169*/   "RADIUS server authentication",
/*170*/   "TACACS authentication server",
/*171*/   "TACACS server authentication",
/*172*/   "Radiuss server authentication",
/*173*/   "RADIUS authentication server",
/*174*/   "Defines login authentication method/precedence",
/*175*/   "Banner info",
/*176*/   "Configures banner information",
/*177*/   "The name of the responsible company",
/*178*/   "Company name",
/*179*/   "Information about the DC power supply",
/*180*/   "The floor where the equipment is located",
/*181*/   "Specifies the floor where the equipment is located",
/*182*/   "The row where the equipment is located",
/*183*/   "Specifies the row where the equipment is located",
/*184*/   "The rack where the equipment is located",
/*185*/   "Specifies the rack where the equipment is located",
/*186*/   "The electrical circuit",
/*187*/   "Specifies the electrical circuit",
/*188*/   "The name of the responsible department",
/*189*/   "Department string",
/*190*/   "Information about the equipment",
/*191*/   "Manufacturer's ID",
/*192*/   "Specifies the manufacturer's ID",
/*193*/   "The shelf in the rack",
/*194*/   "Specifies the shelf in the rack",
/*195*/   "Manufacturer name",
/*196*/   "Specifies manufacturer name",
/*197*/   "The physical location of the equipment - city and street address",
/*198*/   "Specifies the physical location of the equipment",
/*199*/   "IP address and mask for the equipment",
/*200*/   "Specifies IP address and mask for the equipment",
/*201*/   "The LP number",
/*202*/   "Specifies the LP number",
/*203*/   "Name and telephone to contact the manager (can configure 3 managers)",
/*204*/   "Manager's name",
/*205*/   "Specifies manager's name",
/*206*/   "Manager's telephone number",
/*207*/   "Specifies manager's telephone number",
/*208*/   "Position of the equipment in the MUX",
/*209*/   "Specifies position of the equipment in the MUX",
/*210*/   "Additional information",
/*211*/   "Specifies additional information",
/*212*/   "Boot commands",
/*213*/   "Specifies the image used to start up the system",
/*214*/   "Boot ROM image",
/*215*/   "Inputs a file or an image",
/*216*/   "Configuration file",
/*217*/   "Runtime code",
/*218*/   "Creates or modifies a class map",
/*219*/   "Match any one",
/*220*/   "Clock",
/*221*/   "Summer time",
/*222*/   "Specifies the name of zone when summer time in effect",
/*223*/   "Date mode",
/*224*/   "April",
/*225*/   "Date",
/*226*/   "Year",
/*227*/   "Hours",
/*228*/   "Minitues",
/*229*/   "Offset",
/*230*/   "August",
/*231*/   "December",
/*232*/   "February",
/*233*/   "January",
/*234*/   "July",
/*235*/   "June",
/*236*/   "March",
/*237*/   "May",
/*238*/   "November",
/*239*/   "October",
/*240*/   "September",
/*241*/   "Predefined mode",
/*242*/   "Australia",
/*243*/   "Europe",
/*244*/   "New Zealand",
/*245*/   "USA",
/*246*/   "Recurring Mode",
/*247*/   "Weeks",
/*248*/   "Friday",
/*249*/   "Monday",
/*250*/   "Saturday",
/*251*/   "Sunday",
/*252*/   "Thursday",
/*253*/   "Tuesday",
/*254*/   "Wednesday",
/*255*/   "Time zone",
/*256*/   "Time zone name",
/*257*/   "Time zone hours",
/*258*/   "After (east of) UTC",
/*259*/   "Before (west of) UTC",
/*260*/   "Time zone minutes",
/*261*/   "",
/*262*/   "Configures congestion notification settings",
/*263*/   "Configures the priority for CNM transmission",
/*264*/   "Priority value",
/*265*/   "Configures settings for a CNPV",
/*266*/   "Configures administrative alternate priority",
/*267*/   "Configures defense mode",
/*268*/   "Defense mode and alternate priority is chosen automatically",
/*269*/   "CN capability is administratively disabled",
/*270*/   "CNPV is remapped to non-CNPV and CN-TAG is removed",
/*271*/   "Priority remapping is inhibited and CN-TAG is removed",
/*272*/   "Priority remapping is inhibited and CN-TAG is retained",
/*273*/   "Control plane",
/*274*/   "Configures 802.1X port-based access control",
/*275*/   "Sets 802.1X global/port settings to default values",
/*276*/   "Specifies EAPOL frames pass-through",
/*277*/   "Sets 802.1X global control",
/*278*/   "Configures ECMP",
/*279*/   "Configures load balancing of ECMP",
/*280*/   "Selection based on destination IP address and L4 port",
/*281*/   "Selection based on hash selection list",
/*282*/   "Specifies index of hash selection list",
/*283*/   "Modifies enable password parameters",
/*284*/   "Assigns the privileged EXEC password",
/*285*/   "Specifies password in plain text",
/*286*/   "Assigns the password",
/*287*/   "Specifies password in encrypted form",
/*288*/   "Password level",
/*289*/   "Privilege EXEC",
/*290*/   "Exits from global configure mode",
/*291*/   "Configures fan speed",
/*292*/   "Force to full speed",
/*293*/   "Configures hash-selection",
/*294*/   "Configures hash-selection list",
/*295*/   "Configures hash-selection index",
/*296*/   "Configures hash-selection for IPv4",
/*297*/   "Configures hash-selection for IPv6",
/*298*/   "Configures hash-selection for MAC",
/*299*/   "Sets system's network name",
/*300*/   "Specifies or modifies the host name for this device",
/*301*/   "Enters privileged interface configuration mode",
/*302*/   "Craft port",
/*303*/   "Loopback interface",
/*304*/   "Loopback interface number",
/*305*/   "Port channel",
/*306*/   "Virtual LAN interface",
/*307*/   "Global IP configuration subcommands",
/*308*/   "Binds a port to an IP ACL",
/*309*/   "Ingress packet",
/*310*/   "Enables counter",
/*311*/   "Specifies the default gateway",
/*312*/   "IP address of the default gateway",
/*313*/   "Dynamic Host Configuration Protocol",
/*314*/   "DHCP relay agent parameters",
/*315*/   "Relay agent information option",
/*316*/   "Insert relay informationin BOOTREQUEST",
/*317*/   "Format of sub-options in option 82",
/*318*/   "Do not using subtype in sub-option",
/*319*/   "Relay agent information remote ID sub-option",
/*320*/   "Inserts ip address in remote ID sub-option",
/*321*/   "Remote ID encode type",
/*322*/   "Encodes characters as ascii code",
/*323*/   "Encodes characters as hex code",
/*324*/   "Inserts mac address in remote ID sub-option",
/*325*/   "configured string",
/*326*/   "Inserts string in remote ID sub-option",
/*327*/   "Defines forwarding Policy",
/*328*/   "Do not forward BOOTREQUEST message with existing information",
/*329*/   "Leave existing information alone",
/*330*/   "Replace existing information",
/*331*/   "DHCP relay server",
/*332*/   "Server IP address 1",
/*333*/   "Server IP address 2",
/*334*/   "Server IP address 3",
/*335*/   "Server IP address 4",
/*336*/   "Server IP address 5",
/*337*/   "Specifies domain-list name",
/*338*/   "Specifies domain lookup",
/*339*/   "Specifies domain name",
/*340*/   "Specifies host",
/*341*/   "Specifies host name or alias",
/*342*/   "Specifies host IP address",
/*343*/   "HTTP server configuration",
/*344*/   "Authentication",
/*345*/   "Authentication, Authorization and Accounting settings",
/*346*/   "Sets the method list for EXEC authorization, which applies authorization for starting an EXEC session.",
/*347*/   "Uses the default authorization list.",
/*348*/   "Uses an authorization list with this name",
/*349*/   "Defines the port for the HTTP server",
/*350*/   "Specifies a HTTP port number",
/*351*/   "Secure HTTP port number",
/*352*/   "HTTP port number",
/*353*/   "Enables secure HTTP server",
/*354*/   "Enables HTTP server",
/*355*/   "Specifies name server",
/*356*/   "Specifies name-server IP address",
/*357*/   "Specifies optional name-server IP address",
/*358*/   "Secure Shell server connections",
/*359*/   "Secure Shell retry times",
/*360*/   "Secure Shell authentication retry times",
/*361*/   "Enables Secure Shell",
/*362*/   "Secure Shell server key",
/*363*/   "Sets the Secure Shell server key size",
/*364*/   "Key size of SSH server key",
/*365*/   "Secure authentication timeout",
/*366*/   "Timeout value of Secure Shell",
/*367*/   "Configures Telnet server",
/*368*/   "Max number of Telnet sessions",
/*369*/   "Modifies Telnet server max sessions number",
/*370*/   "Modifies Telnet server port",
/*371*/   "Enables Telnet server",
/*372*/   "Configures TFTP",
/*373*/   "Specifies the maximum number of retries",
/*374*/   "Number of retries",
/*375*/   "Specifies timeout before retry",
/*376*/   "Time in seconds",
/*377*/   "IPv6 configuration commands",
/*378*/   "Binds a port to an IPv6 ACL.",
/*379*/   "Set IPv6 default gateway",
/*380*/   "Specifies one IPv6 address as the default gateway",
/*381*/   "Specifies one IPv6 link-local address with ZoneID as the default gateway",
/*382*/   "Set maxium number of hops of RA and all IPv6 packets",
/*383*/   "The maximum number of hops",
/*384*/   "Add one static entry to IPv6 neighbor discovery cache",
/*385*/   "Specify the IPv6 address of the neighbor",
/*386*/   "Specify the interface type of the interface that this neighbor resides, currently only VLAN is supported",
/*387*/   "Specify the number of the interface that this neighbor resides",
/*388*/   "MAC address",
/*389*/   "Specifies jumbo status",
/*390*/   "Specifies jumbo frame status",
/*391*/   "Enters the line configuration mode",
/*392*/   "LLDP",
/*393*/   "LLDP Hold time Multiplier",
/*394*/   "multiple",
/*395*/   "Specifies the fast start counts",
/*396*/   "Specifies lldp fast start will send how many LLDP paket.",
/*397*/   "LLDP Notification Interval",
/*398*/   "seconds",
/*399*/   "LLDP Transmission Interval",
/*400*/   "LLDP Reinitialization Delay",
/*401*/   "LLDP TX Delay Interval",
/*402*/   "Modifies message logging facilities",
/*403*/   "Logging to facility",
/*404*/   "Local use 0",
/*405*/   "Local use 1",
/*406*/   "Local use 2",
/*407*/   "Local use 3",
/*408*/   "Local use 4",
/*409*/   "Local use 5",
/*410*/   "Local use 6",
/*411*/   "Local use 7",
/*412*/   "Limits syslog messages saved to switch",
/*413*/   "Event history stored in flash memory",
/*414*/   "Emergencies",
/*415*/   "Alerts",
/*416*/   "Critical",
/*417*/   "Errors",
/*418*/   "Warnings",
/*419*/   "Notifications",
/*420*/   "Informational",
/*421*/   "Debugging",
/*422*/   "Event history stored in temporary RAM",
/*423*/   "Logging to host",
/*424*/   "Host IP address",
/*425*/   "Specifies an UDP port",
/*426*/   "Port number",
/*427*/   "Enables logging to all supported destinations",
/*428*/   "Logging to trap",
/*429*/   "Logging trap level",
/*430*/   "System unusable",
/*431*/   "Immediate action needed",
/*432*/   "Critical conditions",
/*433*/   "Error conditions",
/*434*/   "Warning conditions",
/*435*/   "Normal but significant condition",
/*436*/   "Informational messages only",
/*437*/   "Debugging messages",
/*438*/   "Configures MAC access group",
/*439*/   "Specifies MAC access group",
/*440*/   "Configuration of the address table",
/*441*/   "Aging time for entries in the address table",
/*442*/   "Disable aging-time",
/*443*/   "Address aging interval in seconds",
/*444*/   "Sets MAC address table static information",
/*445*/   "Ethernet or port-channel interface",
/*446*/   "Ethernet IEEE 802.3",
/*447*/   "Status delete-on-reset of VLAN",
/*448*/   "Status permanent of VLAN",
/*449*/   "Configures VXLAN network identifier",
/*450*/   "Specifies VXLAN network identifier",
/*451*/   "Configures remote VTEP",
/*452*/   "Configure the mac-authentication",
/*453*/   "Sets the reauthentication time period in seconds",
/*454*/   "Valid value range in seconds",
/*455*/   "Specifies management parameters",
/*456*/   "Adds IP addresses to SNMP, Web and Telnet groups",
/*457*/   "Starting IP address",
/*458*/   "Ending IP address",
/*459*/   "Adds IP addresses to the Web group",
/*460*/   "Adds IP addresses to the SNMP group",
/*461*/   "Adds IP addresses to the Telnet group",
/*462*/   "Memory utilization",
/*463*/   "The falling threshold of memory utilization",
/*464*/   "Threshold (in percentage)",
/*465*/   "The rising threshold of memory utilization",
/*466*/   "Configures MLAG feature",
/*467*/   "Configures a domain",
/*468*/   "Domain ID",
/*469*/   "Specifies the peer-link",
/*470*/   "Port channel interface number",
/*471*/   "Configures a MLAG",
/*472*/   "MLAG ID",
/*473*/   "Specifies the associated domain",
/*474*/   "Specifies the member port",
/*475*/   "Configures the secure port",
/*476*/   "Configures  MAC address aging",
/*477*/   "Configures MAC filter table",
/*478*/   "Filter ID",
/*479*/   "Specifies MAC address mask",
/*480*/   "Mask address",
/*481*/   "Set NLM filter name",
/*482*/   "Log filter name(Range: 1-32 characters).",
/*483*/   "Deletes a class map",
/*484*/   "Port-channel number",
/*485*/   "Port of the HTTP",
/*486*/   "Telnet Server",
/*487*/   "Remove IPv6 default gateway setting",
/*488*/   "Remove entries from IPv6 neighbor discovery cache",
/*489*/   "Specify the IPv6 address of neighbor",
/*490*/   "Specify the interface type, currently only VLAN type is supported",
/*491*/   "Specify the interface number",
/*492*/   "Disable NLM",
/*493*/   "Network Time Protocol configuration",
/*494*/   "Authenticate time sources",
/*495*/   "Authentication key for trusted time sources",
/*496*/   "Key number",
/*497*/   "Accepts time from specified time servers",
/*498*/   "Specifies one or more time servers",
/*499*/   "IP address of time server",
/*500*/   "Deletes a policy map",
/*501*/   "Port channel information",
/*502*/   "Configure load balancing for the port channel",
/*503*/   "Device process",
/*504*/   "CPU utilization",
/*505*/   "The falling threshold of CPU utilization",
/*506*/   "Configs CPU guard status",
/*507*/   "Configs CPU guard high-watermark",
/*508*/   "Configs CPU guard low-watermark",
/*509*/   "Configs CPU guard max-threshold",
/*510*/   "Configs CPU guard min-threshold",
/*511*/   "Configs CPU guard trap status",
/*512*/   "The rising threshold of CPU utilization",
/*513*/   "Unset system's prompt string",
/*514*/   "Quality of Service",
/*515*/   "qos map keyword",
/*516*/   "phb-queue map keyword",
/*517*/   "8 phb values (internal priority)",
/*518*/   "Configures login to RADIUS server",
/*519*/   "Sets the RADIUS server network port",
/*520*/   "Sets the RADIUS encryption key",
/*521*/   "Sets the number of authentication retries",
/*522*/   "Server-Index",
/*523*/   "Sets authentication request interval",
/*524*/   "Configures remote monitoring settings",
/*525*/   "Configures RMON alarm settings",
/*526*/   "Specifies the index of alarm table",
/*527*/   "Configures RMON event settings",
/*528*/   "Specifies the index of event table",
/*529*/   "Configures RSPAN function",
/*530*/   "Configures RSPAN session ID",
/*531*/   "RSPAN session ID",
/*532*/   "Configures RSPAN destination function",
/*533*/   "Configures RSPAN destination port",
/*534*/   "Configures RSPAN Ethernet destination port",
/*535*/   "Configures RSPAN remote settings",
/*536*/   "Configures RSPAN VLAN to carry monitored traffic to the destination port",
/*537*/   "Specifies uplink port in the destination switch",
/*538*/   "Specifies which port(s) will flood RSPAN VLAN traffic",
/*539*/   "Specifies uplink port in the intermediate switch",
/*540*/   "Specifies uplink port in the source switch",
/*541*/   "Configures RSPAN source function",
/*542*/   "Configures RSPAN source port to monitor",
/*543*/   "Configures RSPAN Ethernet source port to monitor",
/*544*/   "Monitors both received and transmitted traffic",
/*545*/   "Monitors received traffic",
/*546*/   "Monitors transmitted traffic",
/*547*/   "Modifies SNMP server parameters",
/*548*/   "Removes SNMP communities",
/*549*/   "SNMP community string",
/*550*/   "Clears the system's contact information",
/*551*/   "Disables SNMP trap function",
/*552*/   "Disables sending SNMP traps",
/*553*/   "Issues authentication failure traps",
/*554*/   "Issues MAC notification traps",
/*555*/   "Configures MAC notification trap interval",
/*556*/   "Clears remote engine ID or resets to the system's default engine ID",
/*557*/   "Local engine ID",
/*558*/   "Remote host",
/*559*/   "Removes SNMP groups",
/*560*/   "Group name string",
/*561*/   "Specifies SNMP version 1",
/*562*/   "Specifies SNMP version 2c",
/*563*/   "Specifies SNMP version 3",
/*564*/   "Specifies security level auth",
/*565*/   "Specifies security level noauth",
/*566*/   "Specifies security level priv",
/*567*/   "Deletes SNMP trap receivers",
/*568*/   "Clears the system's location information",
/*569*/   "Modifies SNMP server notify-filter.",
/*570*/   "notify-filter name string",
/*571*/   "Deletes SNMP users",
/*572*/   "Specifies SNMP user name",
/*573*/   "Deletes SNMP views",
/*574*/   "Specifies view name string",
/*575*/   "Specifies OID tree string",
/*576*/   "Simple Network Time Protocol configuration",
/*577*/   "Sets the interval at which the client polls for time",
/*578*/   "IP address of time server (NTP or SNTP) 1",
/*579*/   "IP address of time server (NTP or SNTP) 2",
/*580*/   "IP address of time server (NTP or SNTP) 3",
/*581*/   "Configures spanning tree parameters",
/*582*/   "Global STA forward time configuration. Range: <4-30 seconds>",
/*583*/   "Global STA hello time configuration. Range: <1-10 seconds>",
/*584*/   "Global STA maximum age configuration. Range: <6-40 seconds>",
/*585*/   "Configures STP, RSTP or MSTP mode",
/*586*/   "Configuration of path cost for RSTP and MST",
/*587*/   "Specifies spanning tree path cost method",
/*588*/   "Specifies spanning-tree priority",
/*589*/   "Specifies spanning-tree transmission limit",
/*590*/   "System wide setting",
/*591*/   "maximum transmission unit",
/*592*/   "TACACS server settings",
/*593*/   "Login TACACS server key",
/*594*/   "Login TACACS server port",
/*595*/   "Specify the server index",
/*596*/   "Sets the time to wait for server reply",
/*597*/   "Configures traffic segmentation",
/*598*/   "Specifies downlink port",
/*599*/   "Specifies the session which uplink/downlink ports belong to",
/*600*/   "Session ID",
/*601*/   "Specifies uplink port",
/*602*/   "Configures traffic of uplink between different sessions",
/*603*/   "Configures upgrade option",
/*604*/   "Configures opcode upgrade option",
/*605*/   "Sets auto upgrade",
/*606*/   "Sets opcode location",
/*607*/   "Specifies whether reload switch automatically when upgrade is done",
/*608*/   "Establishes user name authentication",
/*609*/   "Sets VRRP global configuration",
/*610*/   "Sets VRRP ping enable",
/*611*/   "Configures VXLAN",
/*612*/   "Configures flooding operation",
/*613*/   "Configures multicast group IP address",
/*614*/   "Configures source interface of local VTEP",
/*615*/   "Configures UDP destination port",
/*616*/   "Access port",
/*617*/   "Configures web authentication parameters",
/*618*/   "Configures the maximum unsuccessful login attempts",
/*619*/   "Sets quiet period",
/*620*/   "Configures session timeout period",
/*621*/   "Enables or disables the web-auth function",
/*622*/   "MD5 authentication",
/*623*/   "Authentication key",
/*624*/   "Configures authentication key",
/*625*/   "User name",
/*626*/   "Selection based on destination IP address",
/*627*/   "Selection based on destination MAC address",
/*628*/   "Selection based on source and destination IP address",
/*629*/   "Selection based on source and destination MAC address",
/*630*/   "Selection based on source IP address",
/*631*/   "Selection based on source MAC address",
/*632*/   "Packets per second",
/*633*/   "Set system's prompt string",
/*634*/   "Customizes the CLI prompt",
/*635*/   "queue value",
/*636*/   "from keyword",
/*637*/   "UDP port",
/*638*/   "Key string",
/*639*/   "Retransmit times",
/*640*/   "Server index",
/*641*/   "Sets the port as a host port",
/*642*/   "Specifies the RADIUS server",
/*643*/   "UDP port for RADIUS authentication server (default is 1812)",
/*644*/   "Timeout value",
/*645*/   "Halts and performs a warm restart",
/*646*/   "Configures reloading switch at time",
/*647*/   "Specifies the hour to reload switch",
/*648*/   "Specifies the minute to reload switch",
/*649*/   "Specifies the day to reload switch",
/*650*/   "Specifies the year to reload switch",
/*651*/   "Cancels the specified reload setting",
/*652*/   "Cancels reloading switch at time",
/*653*/   "Cancels reloading switch in time",
/*654*/   "Cancels reloading switch at periodic intervals",
/*655*/   "Configures reloading switch in time",
/*656*/   "Configures reloading switch in hours",
/*657*/   "Specifies reloading switch in hours",
/*658*/   "Configures reloading switch in minutes",
/*659*/   "Specifies reloading switch in minutes",
/*660*/   "Configures reloading switch at periodic intervals",
/*661*/   "Configures reloading switch periodically",
/*662*/   "Reloads switch daily",
/*663*/   "Reloads switch monthly",
/*664*/   "Reloads switch weekly",
/*665*/   "Specifies the OID string to be sampled",
/*666*/   "Specifies the interval in seconds",
/*667*/   "Configures the alarm sample type to be absolute",
/*668*/   "Configures the rising threshold for the sampled statistic",
/*669*/   "Specifies the rising threshold for the sampled statistic",
/*670*/   "Configures the falling threshold for the sampled statistic",
/*671*/   "Specifies the falling threshold for the sampled statistic",
/*672*/   "Configures the alarm owner",
/*673*/   "Specifies the alarm owner",
/*674*/   "Specifies the index of the eventEntry that is used when a falling threshold is crossed",
/*675*/   "Specifies the index of the eventEntry that is used when a rising threshold is crossed",
/*676*/   "Configures the alarm sample type to be delta",
/*677*/   "Configures a comment to describe this event entry",
/*678*/   "Specifies a comment to describe this event entry",
/*679*/   "Configures the entity that configured this entry",
/*680*/   "Specifies the entity that configured this entry",
/*681*/   "Configures an entry in the log table for each event",
/*682*/   "Configures an SNMP trap to sent to one or more management stations",
/*683*/   "Specifies the SNMP community to send trap",
/*684*/   "Sets RSPAN monitored traffic as tagged",
/*685*/   "Sets RSPAN monitored traffic as untagged",
/*686*/   "Defines SNMP community access string",
/*687*/   "Read-only access with this community string",
/*688*/   "Read/write access with this community string",
/*689*/   "Sets the system contact string",
/*690*/   "Identifies contact person for this managed node (Maximum length: 255 characters)",
/*691*/   "Enables SNMP trap function",
/*692*/   "Enables sending of SNMP traps",
/*693*/   "Specifies MAC notification trap interval (seconds)",
/*694*/   "Configures SNMP engine ID",
/*695*/   "Engine ID as hexadecimal string",
/*696*/   "Configures SNMP groups",
/*697*/   "Configures notify view string",
/*698*/   "Specifies notify view string",
/*699*/   "Configures read view string",
/*700*/   "Specifies read view string",
/*701*/   "Configures write view string",
/*702*/   "Specifies write view string",
/*703*/   "Group using the authNoPriv security level",
/*704*/   "Group using the noAuthNoPriv security level",
/*705*/   "Group using SNMPv3 authPriv security level",
/*706*/   "Configures SNMP trap's receivers",
/*707*/   "Informs request notification",
/*708*/   "Retry request notification",
/*709*/   "Counts of retry",
/*710*/   "Sets request notification timeout",
/*711*/   "Timeout in centiseconds",
/*712*/   "Specifies SNMP version",
/*713*/   "Configures UDP port",
/*714*/   "Sets UDP port number",
/*715*/   "Authentication and no privacy security level",
/*716*/   "No authentication and no privacy security level",
/*717*/   "Authentication and privacy security level",
/*718*/   "Sets SNMP version",
/*719*/   "Specifies the system's location information",
/*720*/   "Specifies the location for the system location (Maximum length: 255 characters)",
/*721*/   "Configures SNMP trap users",
/*722*/   "Specifies SNMP group name",
/*723*/   "Configures auth password",
/*724*/   "Specifies authentication type md5",
/*725*/   "Specifies authentication password string that has to be a minimum of 8 characters",
/*726*/   "Configures privacy type and password",
/*727*/   "Use 168 bit 3DES algorithm for encryption",
/*728*/   "Specifies privacy password string",
/*729*/   "Use 128 bit AES algorithm for encryption",
/*730*/   "Use 192 bit AES algorithm for encryption",
/*731*/   "Use 256 bit AES algorithm for encryption",
/*732*/   "Use 56 bit DES algorithm for encryption",
/*733*/   "Specifies authentication type sha",
/*734*/   "Encrypted password",
/*735*/   "Specifies auth password string of 32 hex digits",
/*736*/   "Specifies priv password string of 64 hex digits",
/*737*/   "Specifies priv password string of 32 hex digits",
/*738*/   "Specifies priv password string of 48 hex digits",
/*739*/   "Specifies auth password string of 40 hex digits",
/*740*/   "Specifies priv password string of 40 hex digits",
/*741*/   "Configures authentication password",
/*742*/   "Specifies authentication type MD5",
/*743*/   "Specifies authentication password that has to have a minimum of 8 characters",
/*744*/   "Specifies authentication type SHA",
/*745*/   "Configure auth password",
/*746*/   "Specify auth type md5",
/*747*/   "Configure priv type and password",
/*748*/   "Specify auth type sha",
/*749*/   "Configures SNMP trap views",
/*750*/   "Specifies view type excluded",
/*751*/   "Specifies view type included",
/*752*/   "Seconds of SNTP poll interval",
/*753*/   "Forward time in seconds",
/*754*/   "Hello time in seconds",
/*755*/   "Maximum age in seconds",
/*756*/   "Specifies spanning tree mode as MSTP",
/*757*/   "Specifies spanning tree mode as RSTP",
/*758*/   "Specifies spanning tree mode as STP",
/*759*/   "Specifies MST configuration",
/*760*/   "Enters MST configuration mode",
/*761*/   "Specifies spanning-tree pathcost method as long (0-200000000)",
/*762*/   "Specifies spanning-tree pathcost method as short (0-65535)",
/*763*/   "Spanning-tree priority value in steps of 4096",
/*764*/   "Specifies spanning-tree maximal BPDU transmission hold count",
/*765*/   "Value of spanning-tree transmission limit in seconds",
/*766*/   "Specifies TACACS server key",
/*767*/   "Specifies TACACS server port",
/*768*/   "Specifies the server index",
/*769*/   "Specifies a TACACS server",
/*770*/   "IP address of TACACS server",
/*771*/   "Per-server encryption key (overrides default)",
/*772*/   "The unencrypted (clear text) server key",
/*773*/   "TCP port for TACACS+ server (default is 49)",
/*774*/   "The timeout value",
/*775*/   "Blocks the traffic",
/*776*/   "Forwards the traffic",
/*777*/   "Opcode location",
/*778*/   "Sets user privilege level",
/*779*/   "Normal EXEC",
/*780*/   "No password is required for the user to log in",
/*781*/   "Specifies the password for the user",
/*782*/   "Specifies the encrypted password (Fixed length, 32 characters) for the user",
/*783*/   "Enters VLAN database mode",
/*784*/   "Specifies multicast group IP address",
/*785*/   "Configures VLAN ID",
/*786*/   "Configures physical port interface",
/*787*/   "Specifies the outer UDP destination port number",
/*788*/   "Sets the maximum unsuccessful login attempts",
/*789*/   "Specifies quiet period in seconds",
/*790*/   "Timeout in seconds",
/*791*/   "Specifies destination IP address as hash key",
/*792*/   "Specifies destination L4 port as hash key",
/*793*/   "Exits from hash-selection configure mode",
/*794*/   "Removes hash-selection",
/*795*/   "Specifies protocol ID as hash key",
/*796*/   "Specifies source IP address as hash key",
/*797*/   "Specifies source L4 port as hash key",
/*798*/   "Specifies VLAN ID as hash key",
/*799*/   "Specifies collapsed destination IP address as hash key",
/*800*/   "Specifies collapsed source IP address as hash key",
/*801*/   "Specifies next-header as hash key",
/*802*/   "Specifies sourec L4 port as hash key",
/*803*/   "Specifies destination MAC address as hash key",
/*804*/   "Specifies ethertype as hash key",
/*805*/   "Specifies source MAC address as hash key",
/*806*/   "Exits from privileged EXEC mode",
/*807*/   "Switch Virtual LAN interface",
/*808*/   "Internet protocol",
/*809*/   "Address",
/*810*/   "Netmask",
/*811*/   "IP address / prefix-length",
/*812*/   "Configures IPv6 interface property",
/*813*/   "Adds IPv6 address to the interface",
/*814*/   "Specifies the IPv6 prefix of the form IPv6-address/prefix-length",
/*815*/   "Specifies the EUI-64 keyword to process 64 bits interface ID as address suffix",
/*816*/   "Specifies the full IPv6 address",
/*817*/   "Specifies the link-local keyword to indicate this is a link local address",
/*818*/   "Enables IPv6 process on the interface",
/*819*/   "Unset the IPv6 configuration",
/*820*/   "Removes IPv6 address from interface",
/*821*/   "Specifies the EUI-64 keyword to process 64 bits interface id as address suffix",
/*822*/   "Disables IPv6 process on the interface",
/*823*/   "Configures the capabilities",
/*824*/   "Advertises flowcontrol operation support",
/*825*/   "Enables symmetric operation support",
/*826*/   "Adds a port to a trunk",
/*827*/   "Configures settings for a CNPV on an interface",
/*828*/   "Configuration DCBX port",
/*829*/   "DCBX port mode",
/*830*/   "Specifies auto downstream port mode",
/*831*/   "Specifies auto upstream port mode",
/*832*/   "Specifies configuration source port mode",
/*833*/   "Specifies manual port mode",
/*834*/   "Interface specific description",
/*835*/   "Responses to intrusion when the authentication is failed",
/*836*/   "Blocks traffic when the authentication is failed",
/*837*/   "Joins to a guest VLAN when the authentication is failed",
/*838*/   "Max EAP request/identity packet retransmissions",
/*839*/   "Max request count",
/*840*/   "Max EAP-request packet other than EAP-request/identify retransmissions",
/*841*/   "Allows host connection to 802.1X-authorized ports",
/*842*/   "Mac-base-auth mode",
/*843*/   "Multi-host mode",
/*844*/   "Configures the maximum number of hosts",
/*845*/   "The maximum number of hosts",
/*846*/   "Single-host mode",
/*847*/   "Sets the 802.1X mode on a port interface",
/*848*/   "Requires 802.1X-aware client RADIUS server authorization",
/*849*/   "Configures the port to grant access to all clients",
/*850*/   "Configures the port to deny access to all clients",
/*851*/   "Enable re-authentication on all ports/interfaces",
/*852*/   "Waiting period for new client after maximum request count",
/*853*/   "Quiet period in seconds",
/*854*/   "Client must be re-authenticated within the specified time interval",
/*855*/   "Re-authentication period in seconds",
/*856*/   "Supplicant response timeout",
/*857*/   "Supp-timeout in seconds",
/*858*/   "Time switch waits before re-transmitting EAP packet",
/*859*/   "Transmission period in seconds",
/*860*/   "802.1Qaz configuration",
/*861*/   "Configures ETS mode on interface",
/*862*/   "Negotiates ETS capability by DCBX",
/*863*/   "Force-enables ETS",
/*864*/   "Exits from interface configure mode",
/*865*/   "Enables flow control",
/*866*/   "Historial interface counters information",
/*867*/   "Specifies name",
/*868*/   "Specifies interval (in seconds)",
/*869*/   "Specifies number of buckets",
/*870*/   "Internet Protocol",
/*871*/   "Egress packet",
/*872*/   "Internet protocol v6",
/*873*/   "Neighbor Discovery protocol",
/*874*/   "Configures IPv6 RA Guard",
/*875*/   "Configures LACP status",
/*876*/   "The local side of an aggregate link",
/*877*/   "Configures a port's LACP administration key",
/*878*/   "Administrative key",
/*879*/   "Configures a port's LACP port priority",
/*880*/   "Port priority",
/*881*/   "Combines with MAC address to form LAG identifier",
/*882*/   "System priority",
/*883*/   "The remote side of an aggregate link",
/*884*/   "Configuration LLDP port",
/*885*/   "Administration status",
/*886*/   "Receive only",
/*887*/   "Transmit only",
/*888*/   "Transmit and receive",
/*889*/   "LLDP basic optional TLVs",
/*890*/   "Management Address",
/*891*/   "Port Description",
/*892*/   "System Capabilities",
/*893*/   "System Description",
/*894*/   "System Name",
/*895*/   "DCBX TLVs",
/*896*/   "Specifies to send the ETS ConfigurationTLV",
/*897*/   "Specifies to send the ETS Recommendation TLV",
/*898*/   "Specifies to send the PFC Configuration TLV",
/*899*/   "802.1 Organizationally Specific TLVs",
/*900*/   "Congestion Notification TLV",
/*901*/   "Protocol Identity TLV",
/*902*/   "Port And Protocol VLAN ID TLV",
/*903*/   "pvid",
/*904*/   "VLAN Name TLV",
/*905*/   "802.3 Organizationally Specific TLVs",
/*906*/   "Link Aggregation TLV",
/*907*/   "MAC/PHY Configuration/Status TLV",
/*908*/   "Max Frame Size TLV",
/*909*/   "Sets lldp med location",
/*910*/   "Civic Address LCI",
/*911*/   "Configures one octect ca-type",
/*912*/   "Configures max 32 character ca-value",
/*913*/   "Sets country code",
/*914*/   "Two-letter ISO 3166 country code,  e.g. US",
/*915*/   "Sets location the DHCP entry refers to",
/*916*/   "Location of the DHCP server",
/*917*/   "Location of the network element believed to be closest to the client",
/*918*/   "Location of the client",
/*919*/   "Enable to send MED traps",
/*920*/   "Specifies which type of MED TLVs will be send",
/*921*/   "Specifies to send the inventory TLV",
/*922*/   "Specifies to send the location TLV",
/*923*/   "Specifies to send the MED capability TLV",
/*924*/   "Specifies to send the network policy TLV",
/*925*/   "SNMP notification",
/*926*/   "Configures the MAC authentication",
/*927*/   "Responses to intrusion when the authentication has failed",
/*928*/   "Blocks traffic when the authentication has failed",
/*929*/   "Allows to access network when the authentication has failed",
/*930*/   "Specifies the maximum number of authenticated MAC address",
/*931*/   "The maximum number of authenticated MAC address",
/*932*/   "Enables MAC learning on specified interface",
/*933*/   "Specifies media type",
/*934*/   "Specifies media type as SFP forced",
/*935*/   "Specifies forced 1000BASE-SFP connector",
/*936*/   "Specifies forced 10GBASE-SFP connector",
/*937*/   "Enables negotiation function",
/*938*/   "Configures the dynamic-qos feature",
/*939*/   "Enables dynamic VLAN assignment",
/*940*/   "Specifies guest VLAN",
/*941*/   "Specifies guest VLAN ID",
/*942*/   "Configures the link-detection feature",
/*943*/   "Detects link-down event",
/*944*/   "Specifies intrusion lock action",
/*945*/   "Shutdowns port when detect link down",
/*946*/   "Sends SNMP trap when detect link down",
/*947*/   "Sends SNMP trap and shutdowns port when detect link down",
/*948*/   "Detects link-up event",
/*949*/   "Shutdowns port when detect link up",
/*950*/   "Sends SNMP trap when detect link up",
/*951*/   "Sends SNMP trap and shutdowns port when detect link up",
/*952*/   "Detects link-up or link-down event",
/*953*/   "Shutdowns port when detect link up or link down",
/*954*/   "Sends SNMP trap when detect link up or link down",
/*955*/   "Sends SNMP trap and shutdowns port when detect link up or link down",
/*956*/   "Specifies the maximum number of authenticated MAC address.",
/*957*/   "The maximum number of authenticated MAC address. 0 is the value for no limit.",
/*958*/   "Specifies secure port mode",
/*959*/   "Enables MAC authentication",
/*960*/   "Configures MAC filter",
/*961*/   "Removes the port from the trunk",
/*962*/   "Sets operation mode",
/*963*/   "Sets multi-host maximum MAC number",
/*964*/   "Sets maximum MAC address number",
/*965*/   "Disables flow control",
/*966*/   "VLAN ID TLV",
/*967*/   "Disables MAC learning on specified interface",
/*968*/   "Disables negotiation function",
/*969*/   "Configures dynamic QoS assignment",
/*970*/   "Disables dynamic VLAN assignment",
/*971*/   "Configures Priority-based Flow Control",
/*972*/   "Configures PFC mode on interface",
/*973*/   "Configures PFC priority on interface",
/*974*/   "Configures PFC for given priority",
/*975*/   "Specifies priority value",
/*976*/   "Configures the characteristics of the port",
/*977*/   "Monitors another interface",
/*978*/   "Specifies access-list to be monitored",
/*979*/   "Disables port security",
/*980*/   "Responses to take action when port security is violated",
/*981*/   "Sets port maximum MAC address count",
/*982*/   "cos-dscp map keyword",
/*983*/   "cos values",
/*984*/   "cfi values",
/*985*/   "default drop precedence map keyword",
/*986*/   "dscp-cos map keyword",
/*987*/   "phb values (internal priority)",
/*988*/   "drop precedence values",
/*989*/   "dscp-mutation map keyword",
/*990*/   "DSCP values  (up to 8 values total)",
/*991*/   "ip-port-dscp map keyword",
/*992*/   "tcp protocol",
/*993*/   "destination port number",
/*994*/   "udp protocol",
/*995*/   "interface information",
/*996*/   "set the interface mapping mode to IP precedence or DSCP or cos",
/*997*/   "Assigns priority queues",
/*998*/   "Assign default Scheduling mode (WRR) at the egress ports",
/*999*/   "Assigns default weights to CoS priority queues",
/*1000*/   "Configures rate limits",
/*1001*/   "Specifies the ingress rate limit of a port",
/*1002*/   "Specifies the egress rate limit of a port",
/*1003*/   "Configures RMON collection settings",
/*1004*/   "Configures RMON collection history settings",
/*1005*/   "Configures RMON history control table settings",
/*1006*/   "Specifies the index of history control table",
/*1007*/   "Configures RMON collection statistics settings",
/*1008*/   "Configures rmon statistics control table settings",
/*1009*/   "Specifies the index of statistics control table",
/*1010*/   "Output direction",
/*1011*/   "Shuts down the selected interface",
/*1012*/   "Enables this device to send SNMP traps",
/*1013*/   "Issues link-up or link-down traps",
/*1014*/   "Configures MAC notification trap",
/*1015*/   "Specifies spanning tree configuration",
/*1016*/   "Disables bpdu filtering state",
/*1017*/   "Disables bpdu guard state",
/*1018*/   "Enables BPDU guard auto recovery",
/*1019*/   "Configures the interval for BPDU guard auto recovery",
/*1020*/   "Specifies spanning-tree cost",
/*1021*/   "Specifies spanning-tree edge port",
/*1022*/   "Specifies spanning-tree link type",
/*1023*/   "Specifies spanning-tree MST configuration",
/*1024*/   "Instance ID",
/*1025*/   "Spanning-tree MST cost",
/*1026*/   "Spanning-tree MST priority",
/*1027*/   "Specifies spanning-tree port priority",
/*1028*/   "Disables spanning-tree root-guard",
/*1029*/   "Disables the spanning tree",
/*1030*/   "Don't propagate topology change on this port",
/*1031*/   "Configures switch mode characteristics",
/*1032*/   "Specifies port's acceptable frame types",
/*1033*/   "Configures the allowed VLAN port list",
/*1034*/   "Specifies the VLAN",
/*1035*/   "Configures broadcast storm control",
/*1036*/   "Configures a forbidden port",
/*1037*/   "Configures frame filtering based on VLAN membership",
/*1038*/   "Configures the port mode",
/*1039*/   "Port mtu",
/*1040*/   "Configures multicast storm control",
/*1041*/   "Configures the PVID of the port",
/*1042*/   "Configures 802.1p priorities",
/*1043*/   "Sets the priority for untagged frames",
/*1044*/   "Configures unicast storm control",
/*1045*/   "Configures traffic class",
/*1046*/   "Configures transmission selection algorithm",
/*1047*/   "Specifies traffic-class value",
/*1048*/   "Configures priority to traffic-class mapping",
/*1049*/   "Configures allocated bandwidth of a group on interface",
/*1050*/   "Disable transceiver monitor",
/*1051*/   "Set transceiver-threshold to default value",
/*1052*/   "Set current to default value",
/*1053*/   "Set rx-power to default value",
/*1054*/   "Set temperature to default value",
/*1055*/   "Set tx-power to default value",
/*1056*/   "Set voltage to default value",
/*1057*/   "Disable transceiver threshold auto mode",
/*1058*/   "Enables web authentication",
/*1059*/   "Negotiates PFC capability by DCBX",
/*1060*/   "Force-enables PFC",
/*1061*/   "Monitors received and transmitted traffic",
/*1062*/   "Enables port security",
/*1063*/   "Disables port only",
/*1064*/   "Issues SNMP trap message only",
/*1065*/   "Issues SNMP trap message and disables port",
/*1066*/   "Addresses number",
/*1067*/   "phb value (internal priority)",
/*1068*/   "drop precedence value",
/*1069*/   "default drop precedence value",
/*1070*/   "cos value",
/*1071*/   "cfi value",
/*1072*/   "to keyword",
/*1073*/   "dscp values for ip precedences 0-7",
/*1074*/   "set the interface mapping mode to cos",
/*1075*/   "set the interface mapping mode to DSCP",
/*1076*/   "set the interface mapping mode to IP precedence",
/*1077*/   "Assign scheduling mode for port",
/*1078*/   "Services egress queues in sequential order",
/*1079*/   "Services egress queues in sequential order first, then as wrr",
/*1080*/   "Property of queue 0, 0 for normal queue, 1 for strict queue",
/*1081*/   "Property of queue 1, 0 for normal queue, 1 for strict queue",
/*1082*/   "Property of queue 2, 0 for normal queue, 1 for strict queue",
/*1083*/   "Property of queue 3, 0 for normal queue, 1 for strict queue",
/*1084*/   "Property of queue 4, 0 for normal queue, 1 for strict queue",
/*1085*/   "Property of queue 5, 0 for normal queue, 1 for strict queue",
/*1086*/   "Property of queue 6, 0 for normal queue, 1 for strict queue",
/*1087*/   "Property of queue 7, 0 for normal queue, 1 for strict queue",
/*1088*/   "Shares bandwidth at the egress ports, according packets",
/*1089*/   "Assigns WRR or DRR weights to CoS priority queues",
/*1090*/   "Range of weights assigned to queues",
/*1091*/   "Kilobits per second.",
/*1092*/   "Configures the interval in seconds over which the data is sampled for each bucket",
/*1093*/   "Specifies the interval in seconds over which the data is sampled for each bucket",
/*1094*/   "Configures the requested number of discrete time intervals",
/*1095*/   "Specifies the requested number of discrete time intervals",
/*1096*/   "Enables bpdu filtering state",
/*1097*/   "Enables bpdu guard state",
/*1098*/   "Specifies the BPDU guard auto recovery interval",
/*1099*/   "Spanning-tree cost value",
/*1100*/   "Specifies this port is auto edge port",
/*1101*/   "Specifies spanning-tree link type as auto",
/*1102*/   "Specifies spanning-tree link type as point-to-point",
/*1103*/   "Specifies spanning-tree link type as shared",
/*1104*/   "Spanning-tree port priority value",
/*1105*/   "Spanning-tree port priority value in steps of 16",
/*1106*/   "Enables spanning-tree root-guard",
/*1107*/   "The port accepts all frames, tagged or untagged",
/*1108*/   "The port accepts only tagged frames",
/*1109*/   "Configures allowed VLAN port list",
/*1110*/   "Adds port to the VLAN",
/*1111*/   "VLAN ID list",
/*1112*/   "Sets the port as a tagged member of the VLAN",
/*1113*/   "Sets the port as an untagged member of the VLAN",
/*1114*/   "Removes port from the VLAN",
/*1115*/   "Sets broadcast rate level",
/*1116*/   "Adds VLANs to the current list",
/*1117*/   "Removes VLANs from the current list",
/*1118*/   "Sets as access mode",
/*1119*/   "Combines ports into a common VLAN and maps the VLANs to the port",
/*1120*/   "Combines only tagged/specified ports into a common VLAN and maps the VLANs to the port",
/*1121*/   "Port MTU",
/*1122*/   "MTU size",
/*1123*/   "Sets multicast rate level",
/*1124*/   "The native VLAN ID used for classifying untagged frames on the ingress port",
/*1125*/   "Sets unknown unicast rate level",
/*1126*/   "Enhanced Transmission Selection",
/*1127*/   "Strict Prioriry",
/*1128*/   "Specifies bandwidth in percentage",
/*1129*/   "Enable transceiver monitor",
/*1130*/   "Sets transceiver threshold",
/*1131*/   "Sets current threshold",
/*1132*/   "Sets high alarm threshold",
/*1133*/   "Threshold value (0.01mA)",
/*1134*/   "Sets high warning threshold",
/*1135*/   "Sets low alarm threshold",
/*1136*/   "Sets low warning threshold",
/*1137*/   "Sets threshold rx-power",
/*1138*/   "Threshold value (0.01dBm)",
/*1139*/   "Sets temperature threshold",
/*1140*/   "Threshold value (0.01Celsius)",
/*1141*/   "Sets tx-power threshold",
/*1142*/   "Sets voltage threshold",
/*1143*/   "Threshold value (0.01Volt)",
/*1144*/   "Enable transceiver threshold auto mode",
/*1145*/   "Configures description to the port-channel",
/*1146*/   "Specifies description to the interface",
/*1147*/   "Exits from port-channel configure mode",
/*1148*/   "LACP configuration",
/*1149*/   "LACP admin-key",
/*1150*/   "Configures LACP timeout",
/*1151*/   "Specifies LACP long timeout",
/*1152*/   "Specifies LACP short timeout",
/*1153*/   "Management IP address",
/*1154*/   "Port description",
/*1155*/   "System capabilities",
/*1156*/   "System description",
/*1157*/   "System name",
/*1158*/   "802.1 organizationally specific TLVs",
/*1159*/   "Protocol identity TLV",
/*1160*/   "Port and protocol VLAN ID TLV",
/*1161*/   "VLAN name TLV",
/*1162*/   "802.3 organizationally specific TLVs",
/*1163*/   "Link aggregation TLV",
/*1164*/   "MAC/PHY configuration/status TLV",
/*1165*/   "Max frame size TLV",
/*1166*/   "Adds description to the port-channel",
/*1167*/   "Disables MAC learning on special interface",
/*1168*/   "Configures interface's alias",
/*1169*/   "Interface's alias",
/*1170*/   "Secondary",
/*1171*/   "Virtual",
/*1172*/   "Specifies DHCP client",
/*1173*/   "Specifies DHCP client vendor class id",
/*1174*/   "Specifies DHCP client vendor class id string in hex mode",
/*1175*/   "Specifies DHCP client vendor class id string in hexadecimal",
/*1176*/   "Specifies DHCP client vendor class id string in text mode",
/*1177*/   "Specifies DHCP client vendor class id string in characters",
/*1178*/   "DHCP Relay",
/*1179*/   "DHCP Relay Server",
/*1180*/   "Server IP address",
/*1181*/   "Enable ipv6 address automatic configuration",
/*1182*/   "Sets IPv6 interface MTU",
/*1183*/   "MTU size in bytes",
/*1184*/   "Configures the number of attempts during the process of DAD",
/*1185*/   "Specifies the number of attempts during the process of DAD",
/*1186*/   "Sets managed address configuration flag",
/*1187*/   "Configures the time interval between two consective neighbor solication messages",
/*1188*/   "Specifies the time interval between two consective neighbor solication messages",
/*1189*/   "Sets other stateful configuration flag",
/*1190*/   "IPv6 Routing Prefix Advertisement",
/*1191*/   "Specifies the IPv6 prefix",
/*1192*/   "Default values are used",
/*1193*/   "Valid lifetime",
/*1194*/   "Preferred lifetime",
/*1195*/   "Do not use prefix for autoconfiguration",
/*1196*/   "Do not use prefix for onlink determination",
/*1197*/   "Configures IPv6 router advertisement",
/*1198*/   "Interval between consecutive  IPv6 RA transmissions",
/*1199*/   "Maximum RA interval in seconds",
/*1200*/   "Minimum RA interval in seconds",
/*1201*/   "Configures IPv6 router lifetime",
/*1202*/   "router lifetime",
/*1203*/   "Configures IPv6 default router preference",
/*1204*/   "Preference for the router specified on an interface is high",
/*1205*/   "Preference for the router specified on an interface is low",
/*1206*/   "Preference for the router specified on an interface is medium",
/*1207*/   "To suppress IPv6 router advertisement transmissions",
/*1208*/   "Sets reachable time of neighboring nodes",
/*1209*/   "Sets the reachable time",
/*1210*/   "Dynamic host configuration protocol",
/*1211*/   "Disable ipv6 address automatic configuration",
/*1212*/   "Unsets the IPv6 neighbor discovery configuration",
/*1213*/   "Unsets the IPv6 duplicate address detection setting",
/*1214*/   "Resets the number of attempts during the process of DAD to the default setting",
/*1215*/   "Resets the time interval between two consective neighbor solication messages to the default setting",
/*1216*/   "IPv6 routing prefix advertisement",
/*1217*/   "Resets VRRP configuration",
/*1218*/   "Disables authentication string",
/*1219*/   "Authentication string",
/*1220*/   "Sets IP address",
/*1221*/   "Disables preempt mode",
/*1222*/   "Disables priority level",
/*1223*/   "Disables timers advertisement interval",
/*1224*/   "Timers advertisement interval",
/*1225*/   "Sets VRRP configuration",
/*1226*/   "Group ID",
/*1227*/   "Sets authentication string",
/*1228*/   "Sets preempt mode",
/*1229*/   "Sets preempt mode with delay time",
/*1230*/   "Delay time of preempt mode",
/*1231*/   "Sets priority level",
/*1232*/   "Priority level",
/*1233*/   "Sets timers advertisement interval",
/*1234*/   "Sets number of data bits per character",
/*1235*/   "Sets data bits as 7 bits per character",
/*1236*/   "Sets data bits as 8 bits per character",
/*1237*/   "Sets the inactive timeout",
/*1238*/   "Disabled",
/*1239*/   "Exits from line configure mode",
/*1240*/   "Enables password checking",
/*1241*/   "Local password checking",
/*1242*/   "Sets terminal parity",
/*1243*/   "Sets a password",
/*1244*/   "Sets the password threshold",
/*1245*/   "Sets the amount of time the management console is inaccessible",
/*1246*/   "Sets the transmit and receive speed",
/*1247*/   "Sets async line stop bits",
/*1248*/   "Sets login timeout",
/*1249*/   "Login timeout",
/*1250*/   "Login response timeout",
/*1251*/   "Even parity",
/*1252*/   "No parity",
/*1253*/   "Odd parity",
/*1254*/   "The line login password",
/*1255*/   "Number of failed login attempts",
/*1256*/   "Silent time in seconds",
/*1257*/   "Sets transmit and receive speed to 115200 bps",
/*1258*/   "Sets transmit and receive speed to 19200 bps",
/*1259*/   "Sets transmit and receive speed to 38400 bps",
/*1260*/   "Sets transmit and receive speed to 57600 bps",
/*1261*/   "Sets transmit and receive speed to 9600 bps",
/*1262*/   "One stop bit",
/*1263*/   "Two stop bits",
/*1264*/   "Sets login timeout in seconds",
/*1265*/   "Authorization parameters",
/*1266*/   "Enables EXEC authorization",
/*1267*/   "Sets the amount of time the management telnet is inaccessible",
/*1268*/   "Exits from configured mode",
/*1269*/   "Exits from MSTP configuration mode",
/*1270*/   "Specifies maximum number of hops number",
/*1271*/   "Maximum number of hops",
/*1272*/   "Specifies priority",
/*1273*/   "Switch virtual LAN interface",
/*1274*/   "Value list",
/*1275*/   "Name of MSTP",
/*1276*/   "Specifies revision level",
/*1277*/   "Revision level",
/*1278*/   "return to Privileged EXEC mode",
/*1279*/   "Exits from policy map class configure mode",
/*1280*/   "Defines a policer for classified traffic",
/*1281*/   "flow meter mode",
/*1282*/   "Committed Information Rate Kbps",
/*1283*/   "Committed Burst Size Bytes",
/*1284*/   "Configures conform-action",
/*1285*/   "transmit packets",
/*1286*/   "configures violate-action",
/*1287*/   "drop packets",
/*1288*/   "new IP DSCP value",
/*1289*/   "srtcm-color-aware meter mode",
/*1290*/   "Excess Burst Size Bytes",
/*1291*/   "configures exceed-action",
/*1292*/   "srtcm-color-blind meter mode",
/*1293*/   "Committed Information Rate kbps",
/*1294*/   "trtcm-color-aware meter mode",
/*1295*/   "Peak Information Rate kbps",
/*1296*/   "Peak Burst Size Bytes",
/*1297*/   "trtcm-color-blind meter mode",
/*1298*/   "Classify IP traffic",
/*1299*/   "Specifies CoS value",
/*1300*/   "CoS value",
/*1301*/   "Specifies phb value",
/*1302*/   "phb value",
/*1303*/   "Defines a traffic classification for the policy",
/*1304*/   "Defines the description of policy-map",
/*1305*/   "Returns to Privileged EXEC mode",
/*1306*/   "Exits from policy map configure mode",
/*1307*/   "Deletes a traffic classification for the policy",
/*1308*/   "Redefines the name of policy-map",
/*1309*/   "Absolute time and date",
/*1310*/   "End time and date",
/*1311*/   "Minutes",
/*1312*/   "Specifies the day of the month (ex.: 30)",
/*1313*/   "Specifies the year",
/*1314*/   "Start time and date",
/*1315*/   "Periodic time and date",
/*1316*/   "Daily",
/*1317*/   "To",
/*1318*/   "Weekdays",
/*1319*/   "Weekend",
/*1320*/   "Exits from VLAN configure mode",
/*1321*/   "Specifies VLAN state",
/*1322*/   "VLAN interface media type",
/*1323*/   "Configures Remote SPAN VLAN",
/*1324*/   "The VLAN is operational",
/*1325*/   "The VLAN is suspended. It cannot pass packets",
/*1326*/   "Date and time information",
/*1327*/   "Sets the system time and date information",
/*1328*/   "Seconds",
/*1329*/   "Day of month",
/*1330*/   "Resets functions",
/*1331*/   "Clears ACL hardware statistics",
/*1332*/   "Specifies direction",
/*1333*/   "Ingress",
/*1334*/   "Specifies global statistics",
/*1335*/   "Specifies interface",
/*1336*/   "Clears statistics on an Ethernet port",
/*1337*/   "Egress",
/*1338*/   "Specifies ACL name",
/*1339*/   "Clears ARP cache",
/*1340*/   "Clears counters",
/*1341*/   "Clears statistics on an Ethernet port-channel",
/*1342*/   "Clears all entries in the DNS cache",
/*1343*/   "Clears entries from host name-to-address table",
/*1344*/   "Clears all static entries from the DNS table",
/*1345*/   "Sends ICMP packets to remote hostname",
/*1346*/   "Clears IPv6 related information",
/*1347*/   "Clears all the dynamic entries in IPv6 neighbor discovery cache",
/*1348*/   "Resets all the IPv6 traffic counters",
/*1349*/   "Clears messages from the log buffer",
/*1350*/   "Clears learned entries from forwarding data base",
/*1351*/   "Clears the given learned entry from forwarding database",
/*1352*/   "Clears all learned entries from forwarding database",
/*1353*/   "Clears learned entries of the given interface from forwarding database",
/*1354*/   "Ethernet channel of interface",
/*1355*/   "Clears learned entries of the given VLANs from forwarding database",
/*1356*/   "Clears the entries of the secure port",
/*1357*/   "Clears the entries in the authenticated MAC address table",
/*1358*/   "Specifies the MAC address and removes it",
/*1359*/   "The MAC address",
/*1360*/   "Clears the secure MAC address which is associated with the specified interface",
/*1361*/   "Specifies the Ethernet port number",
/*1362*/   "Learnt secure MAC address",
/*1363*/   "By interface",
/*1364*/   "Clears the secure MAC address which is associated with the specified interface.",
/*1365*/   "Specifies the Ethernet port number.",
/*1366*/   "Authorized secure MAC address",
/*1367*/   "Clears Priority-based Flow Control Statistics",
/*1368*/   "Clears PFC Statistics",
/*1369*/   "Ethernet Channel of interfaces",
/*1370*/   "Policy maps",
/*1371*/   "class maps",
/*1372*/   "Clears hardware statistics",
/*1373*/   "Enters configuration mode",
/*1374*/   "Copies from one file to another",
/*1375*/   "Copies from file system",
/*1376*/   "Copies to file system",
/*1377*/   "Copies to FTP server",
/*1378*/   "Copies to current system configuration",
/*1379*/   "Copies to startup configuration",
/*1380*/   "Copies to TFTP server",
/*1381*/   "Copies to device unit",
/*1382*/   "Copies to usb stick memory",
/*1383*/   "Copies from FTP server",
/*1384*/   "Adds remote running configuration to current system",
/*1385*/   "Copies public-key from FTP server to switch",
/*1386*/   "Copies from current system configuration",
/*1387*/   "Copies from startup configuration",
/*1388*/   "Copies from TFTP server",
/*1389*/   "Copy HTTPS certificate from TFTP server to switch",
/*1390*/   "Copies public-key from TFTP",
/*1391*/   "Copies from device unit",
/*1392*/   "Copies from usb stick memory",
/*1393*/   "Debugging functions",
/*1394*/   "Specifies ARP debug",
/*1395*/   "Specifies DHCP debug",
/*1396*/   "Sets all classified debugging",
/*1397*/   "Sets client debugging",
/*1398*/   "Sets config debugging",
/*1399*/   "Sets database debugging",
/*1400*/   "Sets event debugging",
/*1401*/   "DHCP packets",
/*1402*/   "Sets relay debugging",
/*1403*/   "lacp debugging",
/*1404*/   "LACP database",
/*1405*/   "LACP events",
/*1406*/   "LACP packets",
/*1407*/   "LACPDU detail",
/*1408*/   "LACP state machine",
/*1409*/   "Spanning tree debugging",
/*1410*/   "All Spanning Tree debugging messages",
/*1411*/   "Spanning tree BPDU",
/*1412*/   "Spanning tree topology events",
/*1413*/   "Spanning tree root events",
/*1414*/   "Specifies VXLAN debug",
/*1415*/   "Sets VNI debugging",
/*1416*/   "Specifies VTEP debugging",
/*1417*/   "Deletes a file",
/*1418*/   "Specifies the file name",
/*1419*/   "Name of the configuration file or image name",
/*1420*/   "Specifies the unit identifier in a stackable system",
/*1421*/   "Unit identifier in a stackable system",
/*1422*/   "Delete a file on usbdisk",
/*1423*/   "Deletes the public key for the specified user",
/*1424*/   "Username",
/*1425*/   "Deletes RSA public key",
/*1426*/   "Deletes DSA public key",
/*1427*/   "Lists files on the file system",
/*1428*/   "List files on usbdisk",
/*1429*/   "List files in some path on usbdisk",
/*1430*/   "Returns to normal mode from privileged mode",
/*1431*/   "Terminates an SSH, Telnet, or a console connection",
/*1432*/   "Hardware ralated functions",
/*1433*/   "Hardware related settings",
/*1434*/   "Changes the interface port mode",
/*1435*/   "Configures the port as a single 40G port",
/*1436*/   "Configures the port as four 10G ports",
/*1437*/   "Configures port mode to default setting",
/*1438*/   "IP DHCP",
/*1439*/   "IP DHCP restart",
/*1440*/   "Client",
/*1441*/   "Generates the host key pair (i.e., public and private)",
/*1442*/   "Generates RSA/DSA host key pair",
/*1443*/   "Generates DSA host key pair",
/*1444*/   "Generates RSA host key pair",
/*1445*/   "Clears the RSA/DSA host keys from RAM memory",
/*1446*/   "Clears the DSA host key from RAM memory",
/*1447*/   "Clears the RSA host key from RAM memory",
/*1448*/   "Saves the host key from RAM to flash memory",
/*1449*/   "Linux related function",
/*1450*/   "Enter Linux Shell",
/*1451*/   "Location led operation",
/*1452*/   "Turn location LED off",
/*1453*/   "Turn location LED on",
/*1454*/   "Configures sFlow",
/*1455*/   "Specifies the owner of sFlow receiver",
/*1456*/   "The owner name of sFlow receiver",
/*1457*/   "Configures counter polling",
/*1458*/   "Specifies the interface",
/*1459*/   "Specifies the ethernet port",
/*1460*/   "Specifies the instance",
/*1461*/   "The instance ID",
/*1462*/   "Configures packet sampling",
/*1463*/   "Destination host name",
/*1464*/   "Sends ICMPv6 echo request packets to another host",
/*1465*/   "Destination IPv6 address",
/*1466*/   "Specifies IPv6 link-local address with ZoneID as the destination address",
/*1467*/   "Reboot to hybrid mode",
/*1468*/   "Configures the timeout of sFlow receiver",
/*1469*/   "The value of timeout",
/*1470*/   "Configures the destination of sFlow receiver",
/*1471*/   "The IP address of destination",
/*1472*/   "Configures the maximum size of sFlow receiver datagram",
/*1473*/   "The value of datagram maximum size",
/*1474*/   "Configures the version of sFlow receiver datagram",
/*1475*/   "The datagram format is V4",
/*1476*/   "The datagram format is V5",
/*1477*/   "Configures the socket port of sFlow receiver",
/*1478*/   "The number of socket port",
/*1479*/   "Specifies associated receiver",
/*1480*/   "Configures interval of counter polling",
/*1481*/   "The value of polling interval",
/*1482*/   "Configures rate of packet sampling",
/*1483*/   "The value of sampling rate",
/*1484*/   "Configures the maximum number of bytes that should be copied from a sampled packet",
/*1485*/   "The value of maximum header size",
/*1486*/   "Access groups",
/*1487*/   "Access groups for IP ACLs",
/*1488*/   "Access groups for IPv6 ACLs",
/*1489*/   "Access groups for MAC ACLs",
/*1490*/   "Show ACL hardware statistics",
/*1491*/   "Information of IP ACLs",
/*1492*/   "Information of extended IP ACLs",
/*1493*/   "Information of standend IP ACLs",
/*1494*/   "Information of IPv6 ACLs",
/*1495*/   "Information of extended IPv6 ACLs",
/*1496*/   "Information of standard IPv6 ACLs",
/*1497*/   "Information of MAC ACLs",
/*1498*/   "Shows the percentage of user configured ACL rules as a percentage of total ACL rules",
/*1499*/   "Information of ARP cache",
/*1500*/   "Rules for configured ARP ACLs",
/*1501*/   "Authorization configurations",
/*1502*/   "Displays class maps",
/*1503*/   "Displays congestion notification information",
/*1504*/   "Displays CNPV information",
/*1505*/   "Displays CP information",
/*1506*/   "Specifies CP index",
/*1507*/   "CP index",
/*1508*/   "DCBX",
/*1509*/   "Status of the specified ethernet port",
/*1510*/   "State of each debugging option",
/*1511*/   "Shows ARP debugging option",
/*1512*/   "Shows DHCP debugging option",
/*1513*/   "Shows LACP debugging option",
/*1514*/   "Shows Spanning Tree debugging option",
/*1515*/   "Shows VXLAN debugging option",
/*1516*/   "DNS information",
/*1517*/   "DNS cache information",
/*1518*/   "802.1X content",
/*1519*/   "Specifies a port(s) for re-authentication",
/*1520*/   "802.1X statistics",
/*1521*/   "ECMP information",
/*1522*/   "Load-balance scheme of ECMP",
/*1523*/   "Display priority to traffic-class mapping",
/*1524*/   "Display traffic-class weighting",
/*1525*/   "ethernet",
/*1526*/   "port-channel",
/*1527*/   "Display weight of traffic-class",
/*1528*/   "The interface port mode information",
/*1529*/   "Hash selection lists",
/*1530*/   "Index of hash-selection list",
/*1531*/   "Shows history information",
/*1532*/   "Host information",
/*1533*/   "Shows interface information",
/*1534*/   "Brief interface description",
/*1535*/   "Status of the specified port channel",
/*1536*/   "Historical sample of interface counters information",
/*1537*/   "Specifies name of historical sampling",
/*1538*/   "Shows current statistic",
/*1539*/   "Shows input statistic only",
/*1540*/   "Shows output statistic only",
/*1541*/   "Shows historial statistic",
/*1542*/   "Specifies index of historial statistics",
/*1543*/   "Specifies count of historial statistics",
/*1544*/   "Shows interface status",
/*1545*/   "Status of the specified Ethernet port",
/*1546*/   "Shows status of specified VLAN interface",
/*1547*/   "Shows interface switchport information",
/*1548*/   "Trunk port",
/*1549*/   "Trunk port interface number",
/*1550*/   "Interface of transceiver information",
/*1551*/   "Interface of transceiver-threshold information",
/*1552*/   "Port assignments for IP ACLs",
/*1553*/   "Rules for configured IP ACLs",
/*1554*/   "Loopback ID",
/*1555*/   "Telnet information",
/*1556*/   "Shows TFTP information",
/*1557*/   "Displays statistics about IP traffic",
/*1558*/   "IPv6 information",
/*1559*/   "Port assignments for IPv6 ACLs",
/*1560*/   "Rules for configured IPv6 ACLs",
/*1561*/   "Display IPv6 default gateway",
/*1562*/   "Shows IPv6 interface property information",
/*1563*/   "Keyword to specify whether to show brief output or not",
/*1564*/   "Keyword to specifiy the interface type, currently only VLAN type is supported",
/*1565*/   "Value to specify the interface number",
/*1566*/   "Prefix generated from a local IPv6 prefix pool",
/*1567*/   "Displays IPv6 MTU per destination cache",
/*1568*/   "Displays IPv6 RA Guard Information",
/*1569*/   "Specifies interfaces",
/*1570*/   "Specifies service VLAN to configure",
/*1571*/   "Port-channel",
/*1572*/   "Displays IPv6 neighbor caches",
/*1573*/   "Specifies the interface type",
/*1574*/   "Specifies the interface number",
/*1575*/   "Specifies the IPv6 address of a neighbor",
/*1576*/   "Displays IPv6 traffic statistics",
/*1577*/   "Statistics for LACP protocol messages",
/*1578*/   "Config settings/operational state for local side",
/*1579*/   "Config settings/operational state for remote side",
/*1580*/   "Shows LLDP configuration",
/*1581*/   "Detailed LLDP configuration",
/*1582*/   "Shows LLDP information",
/*1583*/   "LLDP local device information",
/*1584*/   "Detailed information",
/*1585*/   "LLDP remote device information",
/*1586*/   "LLDP statistics",
/*1587*/   "Location LED operation",
/*1588*/   "Show location LED status",
/*1589*/   "Log records",
/*1590*/   "Shows the contents of login buffers",
/*1591*/   "Logging setting",
/*1592*/   "Shows the information of loopback",
/*1593*/   "Specifies the internal method",
/*1594*/   "Configures the interface of a port",
/*1595*/   "Specifies a port to show internal loopback result",
/*1596*/   "MAC access list",
/*1597*/   "Ports assigned to MAC ACLs",
/*1598*/   "Rules for configured MAC ACLs",
/*1599*/   "Address information",
/*1600*/   "Ethernet or port channel-interface",
/*1601*/   "Sorts by address, VLAN or interface",
/*1602*/   "Sorts by address",
/*1603*/   "Sorts by interface",
/*1604*/   "Sorts by VLAN",
/*1605*/   "Shows count",
/*1606*/   "Shows management information",
/*1607*/   "Shows information for all kinds of clients",
/*1608*/   "shows information for HTTP clients",
/*1609*/   "shows information for SNMP clients",
/*1610*/   "shows information for Telnet clients",
/*1611*/   "Displays MLAG information",
/*1612*/   "Specifies a domain",
/*1613*/   "Specifies a MLAG",
/*1614*/   "Shows the entries of the secure port",
/*1615*/   "Displays the 802.1X status for the specified interface",
/*1616*/   "Shows the entries in the authenticated MAC address table",
/*1617*/   "Specifies the secure MAC address",
/*1618*/   "Shows the secure MAC address for the specified interface",
/*1619*/   "Sorts the output result",
/*1620*/   "Sorts the secure MAC address by address increase",
/*1621*/   "Sorts the secure MAC address by interface increase",
/*1622*/   "The mask of the MAC address",
/*1623*/   "MAC filter table",
/*1624*/   "Show notification log",
/*1625*/   "Shows notification log filter name and operation status",
/*1626*/   "Displays Priority-based Flow Control Information",
/*1627*/   "Displays PFC statistics",
/*1628*/   "Displays policy maps",
/*1629*/   "Specifies class map name",
/*1630*/   "Displays policy maps for control plane",
/*1631*/   "Input",
/*1632*/   "Show hardware statistics",
/*1633*/   "Displays policy maps for interface",
/*1634*/   "Output",
/*1635*/   "Port characteristics",
/*1636*/   "Shows the configuration for a mirror port",
/*1637*/   "Shows configuration of ACL-based mirroring",
/*1638*/   "Shows port security information",
/*1639*/   "Displays port security information for the specified interface",
/*1640*/   "Load-balance scheme for the port channel",
/*1641*/   "Shows process CPU guard information",
/*1642*/   "CPU utilization of each task",
/*1643*/   "Public key information",
/*1644*/   "Shows public key for switch",
/*1645*/   "Shows public key for users",
/*1646*/   "Status of the specified Ehternet port",
/*1647*/   "ip-prec-dscp map keyword",
/*1648*/   "phb-queue map",
/*1649*/   "display the current interface mapping mode",
/*1650*/   "Priority queue information",
/*1651*/   "Shows queue mode",
/*1652*/   "Shows weights of every queue",
/*1653*/   "RADIUS server information",
/*1654*/   "Shows the reload settings",
/*1655*/   "Remote monitoring information",
/*1656*/   "Shows the alarm table",
/*1657*/   "Shows the set of data describing an event that has been logged",
/*1658*/   "Shows the historical sample of Ethernet statistics on interfaces",
/*1659*/   "Shows the collection of statistics kept for interfaces",
/*1660*/   "Display status of the current RSPAN configuration",
/*1661*/   "Shows RSPAN session status",
/*1662*/   "Information for interfaces on the running configuration",
/*1663*/   "Shows the sflow information",
/*1664*/   "Simple Network Management Protocol configuration and statistics",
/*1665*/   "Shows SNMP engine ID",
/*1666*/   "Shows SNMP group information",
/*1667*/   "Show snmp notify-filter profile",
/*1668*/   "Shows SNMP user information",
/*1669*/   "Shows SNMP view information",
/*1670*/   "Displays SNMP server configuration",
/*1671*/   "Displays SNMP server traps configuration",
/*1672*/   "Displays SNMP server traps configuration on interfaces",
/*1673*/   "Spanning-tree configuration",
/*1674*/   "Shows brief information",
/*1675*/   "Shows spanning-tree configuration for MST instance",
/*1676*/   "Specifies configuration",
/*1677*/   "Secure shell server connections",
/*1678*/   "Startup system configuration",
/*1679*/   "Maximum transmission unit",
/*1680*/   "TACACS server information",
/*1681*/   "Technical information",
/*1682*/   "Traffic segmentation information",
/*1683*/   "Shows upgrade information",
/*1684*/   "Information about users logged in",
/*1685*/   "Shows virtual LAN settings",
/*1686*/   "Specifies VLAN by ID",
/*1687*/   "Specifies VLAN by name",
/*1688*/   "Shows VRRP",
/*1689*/   "Displays all entries",
/*1690*/   "Shows VRRP interface",
/*1691*/   "Shows VRRP interface VLAN",
/*1692*/   "Shows brief information on VRRP",
/*1693*/   "Shows VRRP group ID interface VLAN ID counters",
/*1694*/   "Shows VRRP interface brief",
/*1695*/   "Shows VRRP router counters",
/*1696*/   "Shows VXLAN information",
/*1697*/   "Shows flooding information",
/*1698*/   "Shows source interface of local VTEP",
/*1699*/   "Shows UDP destination port",
/*1700*/   "Shows VLAN-VNI mapping",
/*1701*/   "Shows VXLAN VTEP information",
/*1702*/   "Displays watchdog status",
/*1703*/   "Shows web authentication configuration",
/*1704*/   "Shows the information of a dedicated port",
/*1705*/   "Shows the port state and the authenticated host counts",
/*1706*/   "Specifies spanning-tree configuration",
/*1707*/   "Re-checks appropriate BPDU format for interface",
/*1708*/   "Port-channel Interface number",
/*1709*/   "Telnet to a specified host",
/*1710*/   "Remote IP address",
/*1711*/   "Telnet server port",
/*1712*/   "Remote host name",
/*1713*/   "Tests subsystem",
/*1714*/   "Excutes loopback on a specified port",
/*1715*/   "Specifies the internal loopback",
/*1716*/   "Configures the interface",
/*1717*/   "Specifies a port to do internal loopback test",
/*1718*/   "Traces routing path",
/*1719*/   "Specifies remote host IP address",
/*1720*/   "Specifies host name",
/*1721*/   "Specifies remote host IPv6 address",
/*1722*/   "Specifies the maximum number of consecutive timeouts allowed before termination",
/*1723*/   "max-failures",
/*1724*/   "Umount a removable device",
/*1725*/   "usb disk",
/*1726*/   "Configures watchdog setting",
/*1727*/   "Configures software watchdog status",
/*1728*/   "Disable the ability of software watchdog",
/*1729*/   "Enable the ability of software watchdog",
/*1730*/   "Re-authenticates a web-auth enabled port",
/*1731*/   "Specifies a interface",
/*1732*/   "Shows which files booted on system power up",

          "Timeout in seconds;0 is for disable",
          "Timeout in seconds",
          "TOTAL_CLI_MSG_NUM" 
};

