/* MODULE NAME:  fdry_ip_source_guard.c
 *
 * PURPOSE: For SNMP to access Brocade's FDRY-IP-SOURCE-GUARD-MIB:
 * 
 * foundry(1991).products(1).switch(1).snSwitch(3).fdryIpSrcGuardMIB(37)
 *
 * NOTES:
 *
 * HISTORY (mm/dd/yyyy)
 *    04/29/2011 - Qiyao Zhong, Created
 *
 * Copyright(C)      Accton Corporation, 2011
 */

/* Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.4 2004/07/28 08:04:58 dts12 Exp $
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "sys_type.h"
#include "sys_adpt.h"
#include "sys_cpnt.h"
#include "leaf_fdry_ip_source_guard.h"
#include "l_stdlib.h"

#include "snmp_mgr.h"
#include "sysORTable.h"
#include "foundry_lib.h"
#include "fdry_ip_source_guard.h"

#if (SYS_CPNT_IP_SOURCE_GUARD == TRUE)
#include "dhcpsnp_pmgr.h"
#include "dhcpsnp_type.h"
#endif  /* (SYS_CPNT_IP_SOURCE_GUARD == TRUE) */

#if (SYS_CPNT_IP_SOURCE_GUARD == TRUE)  /* from near-beginning to end of file */
/* ------------------------------------------------------------------------
 * TABLE NAME - fdryIpSrcGuardIfConfigTable
 * ------------------------------------------------------------------------
 */
oid fdryIpSrcGuardIfConfigTable_variables_oid[] = { 1,3,6,1,4,1,1991,1,1,3,37,1 };

/* variable3 fdryIpSrcGuardIfConfigTable_variables:
 *   this variable defines function callbacks and type return information
 *   for the  mib section
 */
struct variable3 fdryIpSrcGuardIfConfigTable_variables[] =
{
    /* magic number, variable type, ro/rw, callback fn, L, oidsuffix
     *     (L = length of the oidsuffix)
     */
    { LEAF_fdryIpSrcGuardIfEnable, ASN_INTEGER, RWRITE, var_fdryIpSrcGuardIfConfigTable, 3, { 1, 1, 1 }},
};

void init_fdryIpSrcGuardIfConfigTable(void)
{
    /* Register ourselves with the agent to handle our MIB tree
     */
    REGISTER_MIB("fdryIpSrcGuardIfConfigTable", fdryIpSrcGuardIfConfigTable_variables, variable3,
                 fdryIpSrcGuardIfConfigTable_variables_oid);
}

#define FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN  1

BOOL_T fdryIpSrcGuardIfConfigTable_OidIndexToData(UI32_T exact, UI32_T compc,
    oid *compl, UI32_T *ifIndex)
{
    /* get or set
     */
    if (exact)
    {
        /* check the index length
         */
        if (compc != FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN) /* the constant size index */
        {
            return FALSE;
        }
    }

    *ifIndex = compl[0];

    return TRUE;
}

/*
 * var_fdryIpSrcGuardIfConfigTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ above.
 */
unsigned char *var_fdryIpSrcGuardIfConfigTable(struct variable *vp,
    oid *name,
    size_t *length,
    int exact,
    size_t *var_len,
    WriteMethod **write_method)
{
    UI32_T compc = 0;
    oid compl[FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN] = {0};
    oid best_inst[FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN] = {0};

    /* table-specific variables
     */
    DHCPSNP_TYPE_PortInfo_T entry;
    UI32_T lport_ifindex = 0;

    /* dispatch node to set write method
     */
    switch (vp->magic)
    {
        case LEAF_fdryIpSrcGuardIfEnable:
            *write_method = write_fdryIpSrcGuardIfEnable;
            break;

        default:
            *write_method = 0;
            break;
    }

    /* check compc, retrive compl
     */
    SNMP_MGR_RetrieveCompl(vp->name, vp->namelen, name, *length, &compc, compl,
        FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN);

    memset(&entry, 0, sizeof(entry));

    /* dispatch get-exact versus get-next
     */
    if (exact) /* get or set */
    {
        /* extract index
         */
        if (! fdryIpSrcGuardIfConfigTable_OidIndexToData(exact, compc, compl,
            &lport_ifindex))
        {
            return NULL;
        }

        /* get-exact from core layer
         */
        if (DHCPSNP_PMGR_GetPortInfo(lport_ifindex, &entry) != DHCPSNP_TYPE_OK)
        {
            return NULL;
        }
    }
    else /* get-next */
    {
        /* extract index
         */
        fdryIpSrcGuardIfConfigTable_OidIndexToData(exact, compc, compl,
            &lport_ifindex);

        /* Check the length of inputing index. If compc is less than instance
         * length, we should try get {A.B.C.0.0...}, where A.B.C was
         * obtained from the "..._OidIndexToData" function call, and
         * 0.0... was initialized in the beginning of this function.
         * This instance may exist in the core layer.
         */
        if (compc < FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN)  /* incomplete index */
        {
            /* get-exact, in case this instance exists
             */
            if (DHCPSNP_PMGR_GetPortInfo(lport_ifindex, &entry) != DHCPSNP_TYPE_OK)
            {
                /* get-next according to lexicographic order; if none, fail
                 */
                if (DHCPSNP_PMGR_GetNextPortInfo(&lport_ifindex, &entry) != DHCPSNP_TYPE_OK)
                {
                    return NULL;
                }
            }
        }
        else  /* complete index */
        {
            /* get-next according to lexicographic order; if none, fail
             */
            if (DHCPSNP_PMGR_GetNextPortInfo(&lport_ifindex, &entry) != DHCPSNP_TYPE_OK)
            {
                return NULL;
            }
        }
    }

    /* copy base OID (without index) to output
     */
    memcpy(name, vp->name, vp->namelen * sizeof(oid));

    /* assign data to the OID index
     */
    best_inst[0] = lport_ifindex;
    memcpy(name + vp->namelen, best_inst, FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN * sizeof(oid));
    *length = vp->namelen + FDRYIPSRCGUARDIFCONFIGENTRY_INSTANCE_LEN;

    /* dispatch node to read value
     */
    switch (vp->magic)
    {
        case LEAF_fdryIpSrcGuardIfEnable:
            *var_len = 4;

            /* convert core layer value to user value;
             * VAL_ipSrcGuardMode_srcIpMac is not fully supported here
             */
            switch (entry.ip_src_guard_mode)
            {
                case VAL_ipSrcGuardMode_diabled:
                    long_return = VAL_fdryIpSrcGuardIfEnable_false;
                    break;

                case VAL_ipSrcGuardMode_srcIp:
                case VAL_ipSrcGuardMode_srcIpMac:
                    long_return = VAL_fdryIpSrcGuardIfEnable_true;
                    break;

                /* should not happen
                 */
                default:
                    break;
            }
                
            return (u_char *) &long_return;

        default:
            ERROR_MSG("");
            break;
    }

    /* return failure
     */
    return NULL;
}

int write_fdryIpSrcGuardIfEnable(int action,
    u_char *var_val,
    u_char var_val_type,
    size_t var_val_len,
    u_char *statP,
    oid *name,
    size_t name_len)
{
    /* dispatch action
     */
    switch (action)
    {
        case RESERVE1:
            /* check type and length
             */
            if (var_val_type != ASN_INTEGER)
            {
                return SNMP_ERR_WRONGTYPE;
            }
            break;

        case RESERVE2:
            /* check valid values
             */
            switch (*(long *) var_val)
            {
                case VAL_fdryIpSrcGuardIfEnable_true:
                    break;

                case VAL_fdryIpSrcGuardIfEnable_false:
                    break;

                default:
                    return SNMP_ERR_WRONGVALUE;
            }
            break;

        case FREE:
            break;

        case ACTION:
        {
            UI32_T oid_name_length = 15;
            I32_T value = 0;

            /* table-specific variables
             */
            UI32_T ifIndex = 0;
            UI32_T core_val;

            /* extract index
             */
            if (! fdryIpSrcGuardIfConfigTable_OidIndexToData(TRUE,
                name_len - oid_name_length,
                &(name[oid_name_length]),
                &ifIndex))
            {
                return SNMP_ERR_COMMITFAILED;
            }

            /* get user value
             */
            memcpy(&value, var_val, sizeof(I32_T));

            /* convert to value for core layer
             */
            switch (value)
            {
                case VAL_fdryIpSrcGuardIfEnable_true:
                    core_val = VAL_ipSrcGuardMode_srcIp;
                    break;

                case VAL_fdryIpSrcGuardIfEnable_false:
                    core_val = VAL_ipSrcGuardMode_diabled;
                    break;

                default:
                    return SNMP_ERR_WRONGVALUE;
            }
            
            /* set to core layer
             */
            if (DHCPSNP_PMGR_SetIpSourceGuardMode(ifIndex,
                core_val) != DHCPSNP_TYPE_OK)
            {
                return SNMP_ERR_COMMITFAILED;
            }

            break;
        }

        case UNDO:
            break;

        case COMMIT:
            break;
    }

    /* return success
     */
    return SNMP_ERR_NOERROR;
}

/* ------------------------------------------------------------------------
 * FUNCTION NAME - init_fdryIpSrcGuardMIB
 * ------------------------------------------------------------------------
 * PURPOSE  :   The is the entry point into this file for initialisation.
 *
 * INPUT    :   None.
 *
 * OUTPUT   :   None.
 *
 * RETURN   :   None.
 *
 * NOTES    :   None.
 * ------------------------------------------------------------------------
 */
void init_fdryIpSrcGuardMIB(void)
{
    oid fdryIpSrcGuardMIB_oid[] = { 1,3,6,1,4,1,1991,1,1,3,37 };

    /* register individual tables
     */
    init_fdryIpSrcGuardIfConfigTable();

    /* register ourselves in the sysORTable
     */
    REGISTER_SYSOR_ENTRY(fdryIpSrcGuardMIB_oid,
        "Management Information for configuration of IP Source Guard feature.");
}
#endif  /* (SYS_CPNT_IP_SOURCE_GUARD == TRUE); from near-beginning to end of file */
