#!/bin/sh

PREREQ="mdadm mdrun multipath"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


if [ ! -e /sbin/lvm ]; then
	exit 0
fi

cp /sbin/lvm ${DESTDIR}/sbin

exit 0
