void BACKDOOR_MGR_GetChar(void){return;}
void BACKDOOR_MGR_Printf(void){return;}
void BACKDOOR_MGR_Register_SubsysBackdoorFunc_CallBack(void){return;}
void BUFFER_MGR_Allocate(void){return;}
void BUFFER_MGR_Free(void){return;}
void ISC_RemoteCall(void){return;}
void ISC_RemoteReply(void){return;}
void ISC_SendMcastReliable(void){return;}
void L_CHARSET_IsValidFileNameString(void){return;}
void L_CHARSET_TrimTrailingNonPrintableChar(void){return;}
void L_MM_DebugPrintf(void){return;}
void L_MM_Malloc(void){return;}
void STKTPLG_POM_GetMyUnitID(void){return;}
void STKTPLG_POM_GetNextUnit(void){return;}
void SW_WATCHDOG_MGR_RegisterMonitorThread(void){return;}
void SW_WATCHDOG_MGR_ResetTimer(void){return;}
void SYSFUN_CreateMsgQ(void){return;}
int SYSFUN_ExecuteSystemShellEx(void){return 0;}
void SYSFUN_GetExecuteCmdOutput(void){return;}
void SYSFUN_GetRealAOSShellCmd(void){return;}
void SYSFUN_GiveSem(void){return;}
void SYSFUN_ReceiveEvent(void){return;}
void SYSFUN_SendEvent(void){return;}
void SYSFUN_Sleep(void){return;}
void SYSFUN_Sleep_Interruptible(void){return;}
void SYSFUN_SpawnThread(void){return;}
void SYSFUN_TakeSem(void){return;}
void SYS_TIME_GetUtcRealTimeBySec(void){return;}
void UC_MGR_GetSysInfo(void){return;}
void UC_MGR_SetDirtySignature(void){return;}
void _L_MM_AllocateTxBuffer(void){return;}
void _L_MM_Free(void){return;}
void _L_MM_Mref_GetPdu(void){return;}
void _L_MM_Mref_Release(void){return;}
void _L_MM_Mref_SetPduLen(void){return;}
void L_INET_InaddrToSockaddr(void){return;}
void FD_ZERO(void){return;}
void FD_SET(void){return;}
int select(void){return 1;}
