
#ifndef SNMP_TYPE_H
#define SNMP_TYPE_H

/* ------------------------------------------------------------------------
 * FILE NAME - SNMP_TYPE.H
 * ------------------------------------------------------------------------
 * ABSTRACT :
 * Purpose: This package defines the naming constants for the snmp-specific
 *          data type.
 * ------------------------------------------------------------------------
 *  History
 *
 *   jwang     oct/30/2003      new created
 *
 * ------------------------------------------------------------------------
 * Copyright(C)							  	ACCTON Technology Corp. , 2001
 * ------------------------------------------------------------------------
 */

#include "sys_adpt.h"

/* for trace_id of user_id when allocate buffer with l_mm
 */
enum
{
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY5 = 0,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY6,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY7,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY8,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEYSHA1FINGERPRINT,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEYMD5FINGERPRINT,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEYSHA1FINGERPRINT,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEYMD5FINGERPRINT,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY1,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY2,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY3,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY4,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY5,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY1,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY6,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY2,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY7,
    SNMP_TYPE_TRACE_ID_GET_SSHRSAHOSTKEY8,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY3,
    SNMP_TYPE_TRACE_ID_GET_SSHDSAHOSTKEY4,
    SNMP_TYPE_TRACE_ID_HEADER_SSHUSERTABLE,
    SNMP_TYPE_TRACE_ID_VAR_SSHUSERTABLE,
    SNMP_TYPE_TRACE_ID_SNMP_MGR_GETNEXTRUNNINGTRAPRECEIVER_1,
    SNMP_TYPE_TRACE_ID_SNMP_MGR_GETNEXTRUNNINGTRAPRECEIVER_2,
    SNMP_TYPE_TRACE_ID_SNMP_MGR_GETNEXTRUNNINGTRAPRECEIVER_3,
    SNMP_TYPE_TRACE_ID_SNMP_MGR_GETNEXTRUNNINGTRAPRECEIVER_4,
    SNMP_TYPE_TRACE_ID_SNMP_MGR_MALLOC,
    SNMP_TYPE_TRACE_ID_MGR_SETSNMPCOMMUNITYSTATUS,
    SNMP_TYPE_TRACE_ID_MGR_GETRUNNINGSNMPENGINEIDSTATUS,
    SNMP_TYPE_TRACE_ID_IMGR_HANDLEIPCREQMSG,
    SNMP_TYPE_TRACE_ID_MGR_SETSNMPENGINEIDSTATUS,
    SNMP_TYPE_TRACE_ID_MGR_GETSNMPSTATUS,
    SNMP_TYPE_TRACE_ID_MGR_CREATESNMPV3GROUP,
    SNMP_TYPE_TRACE_ID_MGR_CREATESNMPV3USER,
    SNMP_TYPE_TRACE_ID_MGR_CREATESNMPV3VIEW,
    SNMP_TYPE_TRACE_ID_MGR_DELETESNMPV3VIEW,
    SNMP_TYPE_TRACE_ID_MGR_DELETESNMPV3VIEWBYNAME,
    SNMP_TYPE_TRACE_ID_MGR_DELETESNMPV3GROUP,
    SNMP_TYPE_TRACE_ID_MGR_GETENGINEID,
    SNMP_TYPE_TRACE_ID_MGR_GETRUNNINGENGINEID,
    SNMP_TYPE_TRACE_ID_MGR_GETENGINEBOOTS,
    SNMP_TYPE_TRACE_ID_MGR_DELETESNMPV3USER,
    SNMP_TYPE_TRACE_ID_MGR_GETSNMPV3USER,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPV3USER,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGSNMPV3USER,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPV3GROUP,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGSNMPV3GROUP,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPV3VIEWNAME,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPV3VIEW,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGSNMPV3VIEW,
    SNMP_TYPE_TRACE_ID_MGR_SET_ENGINEID,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPCOMMUNITY,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGSNMPCOMMUNITY,
    SNMP_TYPE_TRACE_ID_MGR_CREATESNMPCOMMUNITY,
    SNMP_TYPE_TRACE_ID_MGR_REMOVESNMPCOMMUNITY,
    SNMP_TYPE_TRACE_ID_MGR_ENABLE_SNMP_AGENT,
    SNMP_TYPE_TRACE_ID_MGR_DISABLE_SNMP_AGENT,
    SNMP_TYPE_TRACE_ID_MGR_GET_AGENTSTATUS,
    SNMP_TYPE_TRACE_ID_MGR_GETRUNNINGSNMPAGENTSTATUS,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTTRAPRECEIVER,
    SNMP_TYPE_TRACE_ID_MGR_GETTRAPRECEIVERBYINDEXFORALLVER,
    SNMP_TYPE_TRACE_ID_MGR_GETTRAPRECEIVERBYINDEX,
    SNMP_TYPE_TRACE_ID_MGR_SETTRAPDESTADDRESSBYINDEX,
    SNMP_TYPE_TRACE_ID_MGR_SETTRAPRECEIVERCOMMSTRINGNAMEBYINDEX,
    SNMP_TYPE_TRACE_ID_MGR_SETTRAPRECEIVERSTATUSBYINDEX,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGTRAPRECEIVER,
    SNMP_TYPE_TRACE_ID_MGR_GETTRAPRECEIVER,
    SNMP_TYPE_TRACE_ID_MGR_DELETETRAPRECEIVER,
    SNMP_TYPE_TRACE_ID_MGR_DELETETRAPRECEIVERWITHTARGETADDRNAME,
    SNMP_TYPE_TRACE_ID_MGR_SETTRAPRECEVIER,
    SNMP_TYPE_TRACE_ID_MGR_SETTRAPRECEIVERWITHTARGETADDRNAME,
    SNMP_TYPE_TRACE_ID_MGR_CREATESNMPREMOTEUSER,
    SNMP_TYPE_TRACE_ID_MGR_DELETESNMPREMOTEUSER,
    SNMP_TYPE_TRACE_ID_MGR_GETSNMPREMOTEUSERENTRY,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPREMOTEUSERENTRY,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGSNMPREMOTEUSERENTRY,
    SNMP_TYPE_TRACE_ID_MGR_CREATEREMOTEENGINEID,
    SNMP_TYPE_TRACE_ID_MGR_DELETEREMOTEENGINEID,
    SNMP_TYPE_TRACE_ID_MGR_DELETEREMOTEENGINEIDENTRY,
    SNMP_TYPE_TRACE_ID_MGR_GETSNMPREMOTEENGINEIDENTRY,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPREMOTEENGINEIDENTRY,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTRUNNINGSNMPREMOTEENGINEIDENTRY,
    SNMP_TYPE_TRACE_ID_MGR_GETNEXTSNMPTARGETADDRTABLE,
    SNMP_TYPE_TRACE_ID_MGR_GETSNMPTARGETADDRTABLE,
    SNMP_TYPE_TRACE_ID_MGR_PACKETS1H,
    SNMP_TYPE_TRACE_ID_MGR_OCTETS1H,
    SNMP_TYPE_TRACE_ID_MGR_BCASTS1H,
    SNMP_TYPE_TRACE_ID_MGR_MCASTS1H,
    SNMP_TYPE_TRACE_ID_MGR_FRAGMENTS1H,
    SNMP_TYPE_TRACE_ID_MGR_COLLISIONS1H,
    SNMP_TYPE_TRACE_ID_MGR_ERRORS1H,
    SNMP_TYPE_TRACE_ID_MGR_PACKETS6H,
    SNMP_TYPE_TRACE_ID_MGR_OCTETS6H,
    SNMP_TYPE_TRACE_ID_MGR_BCASTS6H,
    SNMP_TYPE_TRACE_ID_MGR_MCASTS6H,
    SNMP_TYPE_TRACE_ID_MGR_FRAGMENTS6H,
    SNMP_TYPE_TRACE_ID_MGR_COLLISIONS6H,
    SNMP_TYPE_TRACE_ID_MGR_ERRORS6H,
    SNMP_TYPE_TRACE_ID_MGR_SNMPNOTIFYCREATE,
    SNMP_TYPE_TRACE_ID_MGR_SNMPNOTIFYDEL,
    SNMP_TYPE_TRACE_ID_MGR_SNMPNOTIFYMODIFY,
    SNMP_TYPE_TRACE_ID_MGR_REQSENDTRAP,
    SNMP_TYPE_TRACE_ID_MGR_GETSNMPENABLEAUTHENTRAPS,
    SNMP_TYPE_TRACE_ID_MGR_SETSNMPENABLEAUTHENTRAPS,
    SNMP_TYPE_TRACE_ID_MGR_REQSENDTRAPOPTIONAL,
    SNMP_TYPE_TRACE_ID_MGR_CREATEV3GROUP,
    SNMP_TYPE_TRACE_ID_MGR_CREATEV3VIEW
};


/* For SNMP OID
*/
typedef struct SNMP_TYPE_Oid_S
{
	UI32_T      oid[SYS_ADPT_MAX_OID_COUNT];
	UI32_T      oid_len;
} SNMP_TYPE_Oid_T;

#endif   /* SYS_TYPE_H */
