/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */
#ifndef IP_H
#define IP_H

/* function declarations */
void init_ip(void);
Netsnmp_Node_Handler get_ipReasmFails;
Netsnmp_Node_Handler get_ipFragCreates;
Netsnmp_Node_Handler get_ipInReceives;
Netsnmp_Node_Handler get_ipFragOKs;
Netsnmp_Node_Handler get_ipInUnknownProtos;
Netsnmp_Node_Handler get_ipInAddrErrors;
Netsnmp_Node_Handler get_ipFragFails;
Netsnmp_Node_Handler get_ipInHdrErrors;
Netsnmp_Node_Handler get_ipForwDatagrams;
Netsnmp_Node_Handler do_ipForwarding;
Netsnmp_Node_Handler get_ipOutRequests;
Netsnmp_Node_Handler get_ipInDelivers;
Netsnmp_Node_Handler get_ipRoutingDiscards;
Netsnmp_Node_Handler get_ipReasmReqds;
Netsnmp_Node_Handler get_ipOutNoRoutes;
Netsnmp_Node_Handler do_ipDefaultTTL;
Netsnmp_Node_Handler get_ipReasmTimeout;
Netsnmp_Node_Handler get_ipInDiscards;
Netsnmp_Node_Handler get_ipOutDiscards;
Netsnmp_Node_Handler get_ipReasmOKs;

/* function declarations */
void init_ipAddrEntry(void);
FindVarMethod var_ipAddrEntry;
#define IPADADDR	1
#define IPADIFINDEX	2
#define IPADNETMASK	3
#define IPADBCASTADDR	4
#define IPADREASMMAX	5

/* function declarations */
void init_ipNetToMediaTable(void);
FindVarMethod var_ipNetToMediaTable;
    WriteMethod write_ipNetToMediaPhysAddress;
    WriteMethod write_ipNetToMediaType;
    
    
#define IPNETTOMEDIAIFINDEX		1
#define IPNETTOMEDIAPHYSADDRESS		2
#define IPNETTOMEDIANETADDRESS		3
#define IPNETTOMEDIATYPE		                   4

/* function declarations */
void init_icmp(void);
Netsnmp_Node_Handler get_icmpOutSrcQuenchs;
Netsnmp_Node_Handler get_icmpInAddrMaskReps;
Netsnmp_Node_Handler get_icmpOutAddrMaskReps;
Netsnmp_Node_Handler get_icmpInRedirects;
Netsnmp_Node_Handler get_icmpInTimeExcds;
Netsnmp_Node_Handler get_icmpOutRedirects;
Netsnmp_Node_Handler get_icmpInTimestamps;
Netsnmp_Node_Handler get_icmpOutTimeExcds;
Netsnmp_Node_Handler get_icmpOutTimestamps;
Netsnmp_Node_Handler get_icmpInDestUnreachs;
Netsnmp_Node_Handler get_icmpOutDestUnreachs;
Netsnmp_Node_Handler get_icmpInTimestampReps;
Netsnmp_Node_Handler get_icmpOutTimestampReps;
Netsnmp_Node_Handler get_icmpInEchos;
Netsnmp_Node_Handler get_icmpOutEchos;
Netsnmp_Node_Handler get_icmpInParmProbs;
Netsnmp_Node_Handler get_icmpOutParmProbs;
Netsnmp_Node_Handler get_icmpInEchoReps;
Netsnmp_Node_Handler get_icmpInMsgs;
Netsnmp_Node_Handler get_icmpOutEchoReps;
Netsnmp_Node_Handler get_icmpInAddrMasks;
Netsnmp_Node_Handler get_icmpOutMsgs;
Netsnmp_Node_Handler get_icmpOutAddrMasks;
Netsnmp_Node_Handler get_icmpInErrors;
Netsnmp_Node_Handler get_icmpOutErrors;
Netsnmp_Node_Handler get_icmpInSrcQuenchs;

#endif /* IP_H */
