/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */
#ifndef RIP2GLOBAL_H
#define RIP2GLOBAL_H
#include "leaf_1724.h"

/*These structure only use to snmp*/
typedef struct Rip2PeerEntry_S {
    /* data index */
    /* The IP Address of the Peer System. */
    UI32_T  rip2_peer_address;

    /* The value in the Routing Domain field in RIP packets
       received from the peer. */
	UI8_T  rip2_peer_domain[2];     /* always 0 */

    /* The value of sysUpTime when the most recent RIP update was received
       from this system. */
    UI32_T  rip2_peer_last_update;

    /* RIP version number in the header of the last RIP packet received. */
    /* Value : INTEGER (0 - 255) */
	UI32_T  rip2_peer_version;

    /* The number of invalid RIP response packets  from  this peer */
    UI32_T  rip2_peer_rcv_bad_packets;

    /* The number of invalid routes from this peer that  were ignored */
    UI32_T  rip2_peer_rcv_bad_routes;
} Rip2PeerEntry_T;

/*
 * function declarations
 */
void            init_rip2GlobalRouteChanges(void);
Netsnmp_Node_Handler get_rip2GlobalRouteChanges;

/*
 * function declarations
 */
void            init_rip2GlobalQueries(void);
Netsnmp_Node_Handler get_rip2GlobalQueries;

/*
 * function declarations
 */
void            init_rip2IfStatTable(void);
FindVarMethod   var_rip2IfStatTable;
WriteMethod     write_rip2IfStatStatus;

/*
 * function declarations
 */
void            init_rip2IfConfTable(void);
FindVarMethod   var_rip2IfConfTable;
FindVarMethod   var_rip2IfConfTable;
WriteMethod     write_rip2IfConfDomain;
WriteMethod     write_rip2IfConfAuthType;
WriteMethod     write_rip2IfConfAuthKey;
WriteMethod     write_rip2IfConfSend;
WriteMethod     write_rip2IfConfReceive;
WriteMethod     write_rip2IfConfDefaultMetric;
WriteMethod     write_rip2IfConfStatus;
WriteMethod     write_rip2IfConfSrcAddress;

/*
 * function declarations
 */
void            init_rip2PeerTable(void);
FindVarMethod   var_rip2PeerTable;
FindVarMethod   var_rip2PeerTable;




#endif                          /* RIP2GLOBAL_H */
