/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */
#ifndef DOT1DBASE_H
#define DOT1DBASE_H

/* function declarations */
void init_dot1dBase(void);
Netsnmp_Node_Handler get_dot1dBaseType;
Netsnmp_Node_Handler get_dot1dBaseBridgeAddress;
Netsnmp_Node_Handler get_dot1dBaseNumPorts;

/* function declarations */
void init_dot1dBasePortTable(void);
FindVarMethod var_dot1dBasePortTable;
FindVarMethod var_dot1dBasePortTable;

/* function declarations */
void init_dot1dStp(void);
Netsnmp_Node_Handler get_dot1dStpRootCost;
Netsnmp_Node_Handler do_dot1dStpBridgeMaxAge;
Netsnmp_Node_Handler do_dot1dStpBridgeHelloTime;
Netsnmp_Node_Handler do_dot1dStpBridgeForwardDelay;
Netsnmp_Node_Handler do_dot1dStpPriority;
Netsnmp_Node_Handler get_dot1dStpProtocolSpecification;
Netsnmp_Node_Handler get_dot1dStpMaxAge;
Netsnmp_Node_Handler get_dot1dStpHelloTime;
Netsnmp_Node_Handler get_dot1dStpTimeSinceTopologyChange;
Netsnmp_Node_Handler get_dot1dStpForwardDelay;
Netsnmp_Node_Handler get_dot1dStpHoldTime;
Netsnmp_Node_Handler get_dot1dStpRootPort;
Netsnmp_Node_Handler get_dot1dStpTopChanges;
Netsnmp_Node_Handler get_dot1dStpDesignatedRoot;

/* function declarations */
void init_dot1dStpPortTable(void);
FindVarMethod var_dot1dStpPortTable;
FindVarMethod var_dot1dStpPortTable;
    WriteMethod write_dot1dStpPortPriority;
    WriteMethod write_dot1dStpPortEnable;
    WriteMethod write_dot1dStpPortPathCost;
    
/* function declarations */
void init_dot1dTp(void);
Netsnmp_Node_Handler get_dot1dTpLearnedEntryDiscards;
Netsnmp_Node_Handler do_dot1dTpAgingTime;

/* function declarations */
void init_dot1dTpFdbTable(void);
FindVarMethod var_dot1dTpFdbTable;
FindVarMethod var_dot1dTpFdbTable;

/* function declarations */
void init_dot1dTpPortTable(void);
FindVarMethod var_dot1dTpPortTable;
FindVarMethod var_dot1dTpPortTable;

/* function declarations */
void init_dot1dStaticTable(void);
FindVarMethod var_dot1dStaticTable;
FindVarMethod var_dot1dStaticTable;
    WriteMethod write_dot1dStaticAddress;
    WriteMethod write_dot1dStaticReceivePort;
    WriteMethod write_dot1dStaticAllowedToGoTo;
    WriteMethod write_dot1dStaticStatus;


#endif /* DOT1DBASE_H */
