/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.8 2004/10/14 12:57:34 dts12 Exp $
 */
#ifndef RADIUSACCCLIENT_H
#define RADIUSACCCLIENT_H
/* function declarations */
void init_radiusAccClient(void);
Netsnmp_Node_Handler get_radiusAccClientInvalidServerAddresses;
Netsnmp_Node_Handler get_radiusAccClientIdentifier;

/* function declarations */
void init_radiusAccServerTable(void);
FindVarMethod var_radiusAccServerTable;

/********************************************
 ***********radiusAccServerTable*************
 ********************************************
 */
 
#define RADIUSACCSERVERINDEX       1
#define RADIUSACCSERVERADDRESS       2
#define RADIUSACCCLIENTSERVERPORTNUMBER       3
#define RADIUSACCCLIENTROUNDTRIPTIME       4
#define RADIUSACCCLIENTREQUESTS       5
#define RADIUSACCCLIENTRETRANSMISSIONS       6
#define RADIUSACCCLIENTRESPONSES       7
#define RADIUSACCCLIENTMALFORMEDRESPONSES       8
#define RADIUSACCCLIENTBADAUTHENTICATORS       9
#define RADIUSACCCLIENTPENDINGREQUESTS       10
#define RADIUSACCCLIENTTIMEOUTS       11
#define RADIUSACCCLIENTUNKNOWNTYPES       12
#define RADIUSACCCLIENTPACKETSDROPPED       13

#endif /* RADIUSACCCLIENT_H */
