/* Project Name: ES3526V-60
 * Module Name : xfer_type.h
 * Abstract    :
 * Purpose     : Definitions for the XFER
 *
 * History :
 *          Date        Modifier        Reason
 *          2003/10/22  Erica Li        Create this file
 *
 * Copyright(C)      Accton Corporation, 1999, 2000
 *
 * Note    :
 */

#ifndef _XFER_TYPE_H_
#define _XFER_TYPE_H_

/* INCLUDE FILE DECLARATIONS
 */
#include "sys_type.h"
#include "sys_cpnt.h"

/* NAMING CONSTANT DECLARATIONS
 */
/* These constant should be replay by leaf value
 */
#define XFER_TYPE_MIN_TFTP_RETRY_TIMES   1
#define XFER_TYPE_MAX_TFTP_RETRY_TIMES   16

#define XFER_TYPE_MIN_TFTP_TIMEOUT       1     /* in seconds */
#define XFER_TYPE_MAX_TFTP_TIMEOUT       65535 /* in seconds */

#ifndef	XFER_TYPE_MAX
#define XFER_TYPE_MAX(x1,x2)	((x1) >= (x2) ? (x1) : (x2))
#endif

#define XFER_TYPE_MIN_SIZE_OF_LOCAL_SRC_FILE_NAME       MINSIZE_fileCopySrcFileName
#define XFER_TYPE_MAX_SIZE_OF_LOCAL_SRC_FILE_NAME       SYS_ADPT_FILE_SYSTEM_NAME_LEN

#define XFER_TYPE_MIN_SIZE_OF_LOCAL_DEST_FILE_NAME      MINSIZE_fileCopyDestFileName
#define XFER_TYPE_MAX_SIZE_OF_LOCAL_DEST_FILE_NAME      SYS_ADPT_FILE_SYSTEM_NAME_LEN

#define XFER_TYPE_MAX_SIZE_OF_LOCAL_FILE_NAME           XFER_TYPE_MAX(XFER_TYPE_MAX_SIZE_OF_LOCAL_SRC_FILE_NAME, XFER_TYPE_MAX_SIZE_OF_LOCAL_DEST_FILE_NAME)

#define XFER_TYPE_MIN_SIZE_OF_REMOTE_SRC_FILE_NAME      MINSIZE_fileCopySrcFileName
#define XFER_TYPE_MAX_SIZE_OF_REMOTE_SRC_FILE_NAME      MAXSIZE_fileCopySrcFileName

#define XFER_TYPE_MIN_SIZE_OF_REMOTE_DEST_FILE_NAME     MINSIZE_fileCopyDestFileName
#define XFER_TYPE_MAX_SIZE_OF_REMOTE_DEST_FILE_NAME     MAXSIZE_fileCopyDestFileName

#define XFER_TYPE_MAX_SIZE_OF_REMOTE_FILE_NAME          XFER_TYPE_MAX(XFER_TYPE_MAX_SIZE_OF_REMOTE_SRC_FILE_NAME, XFER_TYPE_MAX_SIZE_OF_REMOTE_DEST_FILE_NAME)


/* xfer_dlft.h
 */
#define XFER_TYPE_DFLT_TFTP_TIMEOUT      5 /* in seconds */

/* DATA TYPE DECLARATIONS
 */
/* for trace_id of user_id when allocate buffer with l_mm
 */
enum
{
    XFER_TYPE_TRACE_ID_XFER_DNLD_TFTP = 0,
    XFER_TYPE_TRACE_ID_XFER_MGR_COPYFILE,
    XFER_TYPE_TRACE_ID_XFER_MGR_REMOTETOSTREAM,
    XFER_TYPE_TRACE_ID_XFER_MGR_STREAMTOREMOTE,
    XFER_TYPE_TRACE_ID_XFER_MGR_STREAMTOLOCAL,
    XFER_TYPE_TRACE_ID_XFER_MGR_LOCALTOSTREAM,
    XFER_TYPE_TRACE_ID_XFER_MGR_UNITTOLOCAL,
    XFER_TYPE_TRACE_ID_XFER_MGR_LOCALTOUNIT,
    XFER_TYPE_TRACE_ID_XFER_MGR_AUTODOWNLOAD,
    XFER_TYPE_TRACE_ID_XFER_MGR_AUTOCONFIGTOUNIT,
    XFER_TYPE_TRACE_ID_XFER_MGR_COPYFILE_SYN,
    XFER_TYPE_TRACE_ID_XFER_MGR_REMOTETOSTREAM_SYN,
    XFER_TYPE_TRACE_ID_XFER_MGR_STREAMTOREMOTE_SYN,
    XFER_TYPE_TRACE_ID_XFER_MGR_COPYTFTPTOSTARTUPOPCODE,
    XFER_TYPE_TRACE_ID_XFER_MGR_GETSWVERSION,
    XFER_TYPE_TRACE_ID_XFER_MGR_COPYLOADER,
    XFER_TYPE_TRACE_ID_XFER_MGR_WRITEFILE,
    XFER_TYPE_TRACE_ID_XFER_MGR_AUTOUPGRADE,
    XFER_TYPE_TRACE_ID_XFER_MGR_GETSWVERSIONFROMONIEINSTALLERFILE,
    XFER_TYPE_TRACE_ID_XFER_MGR_GETSWVERSIONFROMONIEINSTALLERDATA,
    XFER_TYPE_TRACE_ID_XFER_MGR_GETSWFILEVERSION,
    XFER_TYPE_TRACE_ID_XFER_MGR_CHECKIMAGEHEADERVALIDATION,
};

#endif /* end _XFER_TYPE_H_ */


