#!/bin/sh
if ! utils/check_build_env; then
	cd utils
	. ./build_env_init
	cd -
fi

echo "Compiling SDK ..."
make -C ${SDKPROJ} clean
make -C ${SDKPROJ} clean-lib
make -C ${SDKPROJ} all install
[ $? = 0 ] && echo "Done"
