#!/bin/sh
if ! utils/check_build_env; then
    cd utils
    . ./build_env_init
    cd -
fi

echo "<<< Building FRR >>>"

FRR_BUILD_DIR=${ACCPROJ}/user/protocol/frr

echo "### copy src folder to build folder ###"
rm -rf ${FRR_BUILD_DIR}
cp -a ${FRR_SRC_DIR} ${FRR_BUILD_DIR}

cd ${FRR_BUILD_DIR}

echo "### configure ###"
autoreconf -i
./configure \
    --bindir=/usr/bin \
    --sbindir=/usr/bin/frr \
    --sysconfdir=/etc/frr \
    --localstatedir=/var/run/frr \
    --libdir=/usr/lib/frr \
    --includedir=/usr/local/include \
    --datarootdir=/usr/local/share \
    --disable-doc \
    --enable-snmp \
    --enable-multipath=64 \
    --enable-user=frr \
    --enable-group=frr \
    --enable-vty-group=frrvty \
    --enable-configfile-mask=0640 \
    --enable-logfile-mask=0640 \
    --enable-fpm \
    --enable-systemd \
    --with-moduledir=/usr/lib/frr/modules
if [ $? != 0 ] ; then
    echo "ERROR: FRR configure !!!"
    exit 1
fi

echo "### make ###"
make
if [ $? != 0 ] ; then
    echo "ERROR: FRR make !!!"
    exit 2
fi

echo "### make install ###"
make install
if [ $? != 0 ] ; then
    echo "ERROR: FRR make install !!!"
    exit 3
fi

echo "### handle others ###"
${ACCPROJ}/utils/handle_frr_others

[ $? = 0 ] && echo "<<< FRR Done >>>"
