/* MODULE NAME:  udphelper_type.h
 * PURPOSE:
 *     Define common types used in UDP helper.
 *
 * NOTES:
 *
 * HISTORY
 *    04/02/2009 - Lin.Li, Created
 *
 * Copyright(C)      Accton Corporation, 2009
 */
#ifndef _UDPHELPER_TYPE_H
#define _UDPHELPER_TYPE_H

/**********************************
** definitions for return value **
**********************************
*/
enum
{
    UDPHELPER_TYPE_RESULT_FAIL = 0,
    UDPHELPER_TYPE_RESULT_SUCCESS,
    UDPHELPER_TYPE_RESULT_WRONG_VALUE,
    UDPHELPER_TYPE_RESULT_INVALID_ARG,
    UDPHELPER_TYPE_RESULT_CREATE_IF_LIST_FAIL,
    UDPHELPER_TYPE_RESULT_CREATE_IF_HELPER_LIST_FAIL,
    UDPHELPER_TYPE_RESULT_MALLOC_IF_FAIL,
    UDPHELPER_TYPE_RESULT_IF_NOT_EXIST,
    UDPHELPER_TYPE_RESULT_ADDR_NOT_EXIST,
    UDPHELPER_TYPE_RESULT_INSERT_FORWARD_PORT_TO_HASH_FAIL,
    UDPHELPER_TYPE_RESULT_DELETE_FORWARD_PORT_FROM_HASH_FAIL,
    UDPHELPER_TYPE_RESULT_FORWARD_PORT_FULL,
    UDPHELPER_TYPE_RESULT_HELPER_FULL,
    UDPHELPER_TYPE_RESULT_FORWARD_PORT_ARRAY_FAIL,
    UDPHELPER_TYPE_RESULT_SEND_MSG_FAIL,
    UDPHELPER_TYPE_RESULT_BROADCAST,    
    UDPHELPER_TYPE_RESULT_DHCP_RELAY_BACK,
};

#define UDPHELPER_TYPE_BOOTP_CLIENT_PORT 68
#define UDPHELPER_TYPE_BOOTP_SERVER_PORT 67

#define UDPHELPER_TYPE_BOOTP_FLAGS_BROADCAST 32768L

#define UDPHELPER_TYPE_MAX_FORWARD_PORT  65535
#define UDPHELPER_TYPE_MIN_FORWARD_PORT  1

#endif    /* End of _UDPHELPER_TYPE_H */



