#ifndef _CONFIG_AGENT_HEADER_PRIVATE_CONFIG_H_
#define _CONFIG_AGENT_HEADER_PRIVATE_CONFIG_H_

#cmakedefine CONFIG_AGENT_HAVE_LIBXML2 1
#cmakedefine CONFIG_AGENT_HAVE_INIH 1
#cmakedefine CONFIG_AGENT_HAVE_BSON 1
#cmakedefine CONFIG_AGENT_HAVE_MONGOC 1
#cmakedefine CONFIG_AGENT_HAVE_LIBUCL 1
#cmakedefine CONFIG_AGENT_HAVE_PCRE 1

#endif /* _CONFIG_AGENT_HEADER_PRIVATE_CONFIG_H_ */
